### ISSUE TITLE
Unicode in kmonad without X

### ISSUE THREAD

**Issue by WhatisRT** [kmonad/kmonad#143]
I'm currently working on a NixOS module for kmonad, which will start it with the system using systemd. It works nicely, but has problems with Unicode input: when I hit buttons that should insert `ü` or `¹`, they insert `"u` and `^1` respectively.

After investigating a bit, the behaviour seems to be that this is how kmonad behaves right after it's started, and then it switches to inserting the intended characters after a second or so, if I start it from within an X session. However, if I start it in an X session and quickly switch to a TTY, start it from a TTY or manually restart the systemd service, it never switches to inserting the correct characters, even in an X session.

**Comment by slotThe** [comment]
Entering unicode is something that's extremely environment dependent; because `kmonad` reads directly from `uinput`, we can't really do much in this situation and have to rely on the respective environment.  As it is right now, entering unicode is done via X11 compose keys.  Normally, when starting kmonad with your X server, you would have something like 

``` clojure
  output (uinput-sink
          "NAME"
          "setxkbmap -option compose:ralt")
  cmp-seq ralt)
```

in your `defcfg` (the right alt key is the default, so you may not have the `cmp-seq ralt` part).  Obviously, `setxkbmap` needs an active X server to do its thing, so if you start kmonad without anything this will fail.  If you then start your X server afterwards, you will not actually set your compose key to the right thing and `ü` will turn into `"u` (the actual buttons pressed after the compose key).  The solution here is to have `setxkbmap -option compose:ralt` in your `.xinitrc` (or similar) separately.

**Comment by WhatisRT** [comment]
Thanks, that helped! I completely forgot about the `setxkbmap` line in my config, this is also where the 1 second delay came from. I think it would be great if it was mentioned that kmonad handles unicode via the compose key somewhere more prominently, then I probably wouldn't have missed it.

Also, I'm surprised that kmonad requires the compose key for this purpose, this seems like a hack. Is this something we can expect to change at some point?

**Comment by slotThe** [comment]
On Thu, Nov 26 2020 09:28, WhatisRT wrote:
> Thanks, that helped! I completely forgot about the `setxkbmap` line in
> my config, this is also where the 1 second delay came from. I think it
> would be great if it was mentioned that kmonad handles unicode via the
> compose key somewhere more prominently, then I probably wouldn't have
> missed it.

You're right at it should probably be front and center in the README or
something like that.  It is mentioned in the tutorial [1] and while that
information is a bit outdated at this point (it's on my TODO list), the
general idea should still come across.

> Also, I'm surprised that kmonad requires the compose key for this
> purpose, this seems like a hack. Is this something we can expect to
> change at some point?

As I see it (and I honestly really hope I'm wrong on this one and that
someone will correct me) it sort of both is a hack, where it _feels_
wrong to do, but also not, as there is nothing else we can do.  Because
we read via `uinput`, we can only use the input event codes as defined
by the kernel [2].  Unicode interpretation would then have to go on top
of that, which is entirely dependent on the environment one is in; not
only whether you use linux or something else, but also whether you use
X11 or wayland (I *think* the TTY does it via Alt-Codes, but I'm not
sure right now)...  Using compose-key sequences just seems to be the way
things are done in X11 land.

[1] https://github.com/david-janssen/kmonad/blob/master/keymap/tutorial.kbd#L766
[2] https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h

**Comment by WhatisRT** [comment]
Thanks for the explanation! So I guess the less hacky way would be to implement a unified way to send inputs to all these different systems, which seems like a lot of work. Maybe I'll figure out how to set up a compose key in the TTY for the module I'm writing and call it good enough then.

**Comment by 0x1e02** [comment]
I'd really be interested, how you set up the the compose key in the TTY (if you managed to do it at all).

**Comment by david-janssen** [comment]
If he did that would surprise me to no extent. Compose is very much an X11 feature if I'm not mistaken.

**Comment by WhatisRT** [comment]
The solution for my problem was to load the systemd unit after X, see https://github.com/kmonad/kmonad/blob/a2b67f5d45ec2416cc13b2bcb79b9a2c99d06a34/nix/nixos-module.nix#L63
With this, a few things work in the TTY, but not greek letters for example.

**Comment by eighal** [comment]
I'm looking forward to having a kmonad module for NixOS.  Thank you for working on this!

**Comment by slotThe** [comment]
I will close this as "nothing we can do".  Maybe https://github.com/kmonad/kmonad/issues/79 alleviates this
