### ISSUE TITLE
[macOS] Unusable keyboard after kmonad crashes/gets interrupted

### ISSUE THREAD

**Issue by Vermoot** [kmonad/kmonad#159]
This is a big problem.

When I use kmonad on my computer, after some point if kmonad crashes (see #106 for example) or I interrupt it (say to reload it after a config change), my keyboard is completely unresponsive.

At this point I can only ssh into my computer to start kmonad back up or use the accessibility visual keyboard to click click click my way into starting kmonad.

The only way to solve this issue is to reboot.

It doesn't happen right away because at first I can actually stop kmonad and have my keyboard be ok, but after some point (can't say why/how/when) I can't anymore.

I see this in my terminal  
'IOHIDDeviceOpen error: (iokit/common) exclusive access and device already open'  
and I think it might be related, but I'm not sure.

Any ideas?

**Comment by slotThe** [comment]
@thoelze1 is the Mac expert around here; what do you think?

**Comment by thoelze1** [comment]
I don't have any ideas right off the bat. I experienced similar issues during development, but not since. I regularly interrupt kmonad for a config change, but I haven't experienced a crash in months. Maybe crashing has something to do with it...

> At this point I can only ssh into my computer to start kmonad back up or use the accessibility visual keyboard to click click click my way into starting kmonad.
> 
> The only way to solve this issue is to reboot.

Let me make sure I understand you correctly. So once kmonad enters this strange state (randomly, while stopping) your keyboard becomes unresponsive. But once you restart kmonad (via SSH, accessibility keyboard, etc) your keyboard becomes usable again. But upon stopping kmonad, your keyboard returns to its unresponsive state? And this cycle continues until reboot?

> This is a big problem.

Absolutely. I almost stopped developing the macOS interface because issues like this became so frustrating. Are you still using kmonad? If so, is this still happening? Sorry about the delay in responding.

**Comment by Rougemoot** [comment]
> Let me make sure I understand you correctly. So once kmonad enters this strange state (randomly, while stopping) your keyboard becomes unresponsive. But once you restart kmonad (via SSH, accessibility keyboard, etc) your keyboard becomes usable again. But upon stopping kmonad, your keyboard returns to its unresponsive state? And this cycle continues until reboot?

Absolutely, yes, and I have no idea how to fix that short of rebooting.

I stopped using kmonad a while ago because I've started using my mechanical (qmk) keyboard, and on my macbook switched back to Karabiner for stability (and combos), but I'll be happy to try some stuff for you if you need any testing.

**Comment by thoelze1** [comment]
Nothing's jumping out at me yet. For future reference, please provide the following from the time of the bug, if you have it:

- macOS version
- commit you built kmonad from
- config file

Did you have Karabiner running at any point while running kmonad? And how many keyboards were you using? Did all of them become unresponsive? Thanks.

**Comment by Rougemoot** [comment]
Uh, as I said I haven't used kmonad in a while now but the macOS version was Mojave (10.14.6), the commit I built from.... I have no idea really but it must have been right around the time I initially started this issue, and the config file can be found [here](https://github.com/david-janssen/kmonad/blob/master/keymap/user/Rougemoot/applekeeb.kbd).

I never had Karabiner running at the same time as kmonad because of course only one could be used at the same time. I was only using the built-in keyboard on my macbook.

**Comment by david-janssen** [comment]
Hey, just popping in to ask, is this still an issue? I do my KMonad development stuff on a secondary keyboard, so if everything breaks completely, usually plugging my keyboard out and in again fixes things. However, not sure how this is currently on mac.

**Comment by Rougemoot** [comment]
I haven't been using kmonad for several months now, and I've done a full clean install of the newest version of macOS since then, so I couldn't really say. I'm just getting back into re-using it now so we'll see, but I guess for now just go with "no" until the problem reappears and if it does I'll come back here and tell you.

**Comment by nightscape** [comment]
I am using kmonad on Big Sur, and the problem was still occurring in the develop branch a few weeks ago. I haven't pulled and recompiled in a while, but will do do soon. I'll let you know if it's gone now.

**Comment by david-janssen** [comment]
Cool, because there is now no longer a `develop`, only 1 branch to rule them all. If there's no issue with that version, then I'll close this issue.

**Comment by dmsnell** [comment]
Today I experienced the same issue: been using `kmonad` on an off for about a year (to remap my MacBook Pro's built-in keyboard) and I do keep extra keyboards around for cases like this (this also makes me scared to start `monad` as a system service at boot).

Built from 0.4.0-294-g744c044 (744c0445ac9beaece489cd6cdc981eeae45467a7).
Running on Monterey 12.3.1

<details><summary><code>dmsnell.kbd</code></summary>
<pre><code>
;; See keymap/tutorial.kbd for a more complete tutorial

(defcfg
  input (iokit-name "Apple Internal Keyboard / Trackpad")
  output (kext)
  fallthrough true
)

(defsrc
  esc  f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft z    x    c    v    b    n    m    ,    .    /    rsft up
  fn   lctl lalt lmet           spc            rmet ralt left down rght
)

;; Below, I use `around' to compose `layer-toggle' with `fn' (instead
;; of using `layer-toggle' directly) so that the `fn' keypress
;; actually gets emitted. This matters when using an application that
;; can use `fn' as a modifier (like Emacs).

(defalias 
  ;; layer jumping
  fn  (around (layer-toggle apple) fn)
  lA (tap-hold-next-release 200 3 (layer-toggle lA))
  lB (tap-hold-next-release 200 a (layer-toggle lB))
  lE (tap-hold-next-release 200 ; (layer-toggle lE))

  ;; home-row modifiers
  a_s (tap-hold-next-release 200 s lalt)
  a_l (tap-hold-next-release 200 l lalt)

  s_d (tap-hold-next-release 200 d lsft)
  s_k (tap-hold-next-release 200 k lsft)

  c_f (tap-hold-next-release 200 f lctl)
  c_j (tap-hold-next-release 200 j lctl)

  m_a (tap-hold-next-release 200 a lmet)
  m_; (tap-hold-next-release 200 ; lmet)

  m_g (tap-hold-next-release 200 g lmet)
  m_h (tap-hold-next-release 200 h lmet)

  ;; space cadet
  lcd (tap-hold-next 200 \( lsft)
  rcd (tap-hold-next 200 \) lsft)

  ;; other
  cpl (tap-hold-next 200 esc lctl)
  bsp (tap-hold-next 200 bspc lmet)
  ent (tap-hold-next 200 enter rmet)
)

(deflayer default
  _    brdn brup lp   mctl bldn blup prev pp   next mute vold volu
  _    _    _    @lA  _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  @cpl @lB  @a_s @s_d @c_f @m_g @m_h @c_j @s_k @a_l @lE  _    _
  @lcd _    _    _    _    _    _    _    _    _    _    @rcd _
  @fn  _    _    @bsp        _                 @ent _    _    _    _
)

(deflayer lA
  _    _    _    _    _    _    _    _    _    _    _     _    _
  _    _    _    _    _    _    _    _    _    _    _     _    _    _
  _    _    _    _    _    _    pgup home up   end  _     _    _    _
  _    _    lalt lsft lctl lmet pgdn left down right _    _    _
  _    _    _    _    _    _    _    _    _    _    _     _    _
  _    _    _    _              _              _    _     _    _    _
)

(deflayer lB
  _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    '    7    8    9    *    _    _    _
  _    _    lalt lsft lctl lmet =    4    5    6    +    _    _
  _    _    _    _    _    _    -    1    2    3    /    _    _
  _    _    _    _              0              .    _    _    _    _
)

(deflayer lE
  _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    !    @    {    }    |    _    _    _    _    _    _    _    _
  _    #    $    \(  \)    `    rmet rctl rsft ralt _    _    _
  _    %    ^    [    ]    ~    _    _    _    _    _    _    _
  _    _    _    _              _              _    _    _    _    _
)

(deflayer transparent
  _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _              _              _    _    _    _    _
)

(deflayer apple
  ;; this is a safe-guard!!!
  ;; don't change because if the Keyboard
  ;; get's messed up this will set it to
  ;; the hardware default
  esc  f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft z    x    c    v    b    n    m    ,    .    /    rsft up
  fn   lctl lalt lmet           spc            rmet ralt left down rght
)
</code></pre>
</details>

### Notes

 - The way I usually use `kmonad` is to leave open a shell and run it in the foreground. When I want to stop it or update the config I send <kbd>Ctrl</kbd> + <kbd>c</kbd> to kill it.
 - Normally it's fine when killing and my keyboard continues working.
 - Now that it's leaving the keyboard unresponsive I've started and stopped it a number of times with an external keyboard. Sometimes it dies without message, sometimes it prints an error, here are some I've seen:
    - `Encountered error in KeySource: [Cannot interpret mac switch: 124802601320576,Cannot translate from mac keycode: (5,4294967295)]`
    - `Encountered error in KeySource: [Cannot translate from mac keycode: (0,0)]`
 - After rebuilding from c43a0180a3b9ca9c4ff4a283b17369fc4e8e46e2 and running again it's still dropping my keyboard when killing the app (thought I believe the only update there was a Nix module).
 - It doesn't appear to matter if I send the <kbd>Ctrl</kbd>+<kbd>c</kbd> from my built-in laptop keyboard or the external one.

---

One final note since this is my first post on your repo: thanks so much for your work on this. The more I get accustomed to my split keyboard the more I wish my laptop keys could do different things and `kmonad` helps with that. 🙇‍♂️
