### ISSUE TITLE
The maintainer is trying to maintain and could use some direction

### ISSUE THREAD

**Issue by david-janssen** [kmonad/kmonad#180]
First of all: thank you to everyone in the community who has been helping answer questions and resolve issues. In particular I would also like to thank @slotThe for keeping up with pull-requests.

My symptoms have stabilized just a bit for the moment. Things might get worse again, or they might get better, but for now I am trying to invest a little bit of time (a couple of hours a week) into KMonad. I've started working on the Keycode issue (Mac vs Linux vs Windows), which I think was still causing crashes for Mac users, right?

Beyond that, I think you guys have a much better overview of what needs my immediate attention, so I've opened this issue so that you can direct my attention. What is currently the most urgent or troublesome issue?

**Comment by slotThe** [comment]
Glad to hear you're feeling better!  It's been pretty difficult for me to keep up, let alone write code myself, but I tried my best :) 

> I've started working on the Keycode issue (Mac vs Linux vs Windows), which I think was still causing crashes for Mac users, right?

This seems to be the case; at least people still post in the respective issues.  This is probably the "most urgent" bug we have right now, so nice that you're already looking into it!

Other things that I would say are semi-important:

  - #166 (fixed by #167, needs your okay if that's actually what `around-next` was supposed to do from the start; if not then that would turn into a feature request)
  - Possibly #170, because I'm honestly completely lost on that one and am not even sure if it's a kmonad issue
  - Perhaps some thoughts in #157 on what the best way for @elkowar to continue would be.  There's no code yet (and the idea is that we don't write any :), so this may not take too long.  

There are some new feature requests (#174, #165, #163 [for which a half-working implementation exists in #168]) but I would classify those as "low priority".

Other opinions are of course welcome!

**Comment by david-janssen** [comment]
Thanks so much, this is exactly what I needed.

Just to keep everything centralized for the moment.

#166 is now fixed, but waiting for you to either give me the OK or update the pull-request.
#170 I have no idea either, moved to the bottom of the bottom of the pile
#157 Joined the brainstorm
#174 Postponed until new features
#165 Nixed for reasons detailed there
#163 Postponed until new features

I'll get to fixing the keycode issue and then implementing the changes to core to implement #174 and #163

**Comment by focusaurus** [comment]
Glad you are feeling well enough to work on this again!

> I've started working on the Keycode issue (Mac vs Linux vs Windows), which I think was still causing crashes for Mac users, right?

Yes, #106 I believe is still a blocker for me. I haven't been able to participate as much because that bug crashes kmonad for me on my daily driver setup (ergodox on mac) with a keycode I hit literally every 30s so I'm pretty much dead in the water. If I could get kmonad to run without crashing and a working launchd setup so it runs on login and doesn't require babysitting, then I could start running it again and would love to contribute more.

**Comment by slotThe** [comment]
This is out-of-date by now, so I'm closing (we managed to move forward some things here though!)
