### ISSUE TITLE
Can I use kmonad together with qmk layers? (pointer/MIDI/..)

### ISSUE THREAD

**Issue by molleweide** [kmonad/kmonad#225]
Hi guys,

I have another question regarding using kmonad together with
QMK:

Would it be possible to put qmk layer switches on keys marked with XX as
long as I make sure my other layers are fully separated from kmonad
so that I can `exit` kmonad kind of by switching to eg. a mouse
pointer layer.

```lisp
; ergodox ez keymap

; _ underscors denote my 3 by 5 minimal layout real estate that I use with
; kmonad. This is suppose to be/is my daily workhorse layout. Two thumb
; keys for kmonad :)
(deflayer on
  XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX
  XX   _    _    _    _    _    XX   XX   _    _    _    _    _    XX
  XX   _    _    _    _    _              _    _    _    _    _    XX
  XX   _    _    _    _    _    XX   XX   _    _    _    _    _    XX
  XX   XX   XX   _    _                        _    _    XX   XX   XX
                           XX   XX   XX   XX
                                XX   XX
                      XX   XX   XX   XX   XX   XX
)
```

I use three extra qmk specific layers on daily basis

1. MIDI DEVICE LAYER
2. MOUSE POINTER LAYER
    i don't use mouse at all when I use my mechanical board
3. RESET 
    layer where I keep a hidden `RESET` button for quick reflashing

As a plan B I am trying to figure out if I can solve this some other way
by doing some hack or whatever. First I wanted to check with you guys here first for feedback.

What do you guys think?

**Comment by david-janssen** [comment]
Hey there, 

I'm not sure exactly what you mean, but let me give you a bit of an explanation of some kmonad basic concepts and then if that doesn't answer your question, I'd invite you to try again so I can have another shot :-).

The `defsrc` layer isn't actually a geometric layer at all, and internally it just gets represented as an unsorted hashmap. The strict layout that most kmonad configs do is just to make the configuration as visually clear as possible, you want to see *as clearly as you can* exactly what maps correspond to what.

So: you can specify QMK-layer-toggles anywhere you want, it is completely irrelevant. The only thing that kmonad does is:
- Lines up all the entries in your 'defsrc'
- With all of the entries in your layers
Then it creates a 'src-keycode' to 'kmonad-button' correspondence and will run with that keymap. If you send keys that it doesn't recognize it will either ignore them, or rethrow them (depending on the fallthrough parameter in the config). QMK layer switches don't emit any keycodes to the system, so KMonad will be completely ignorant of what is happening anyways. The only danger is if you switch your keyboard by QMK to a different layout, it will no longer line up with what you specified in kmonad, so the *geometric* correspondence between your config and the kmonad map no longer lines up. However, if you told kmonad 'in layer 5, turn all `a`s into `b`s', then as long as you are in layer 5, any `a`, regardless of what button you pushed to trigger it, gets turned into a `b`.

In regards to mouse-pointer stuff, we only grab the keyboard event file, I think. I think QMK devices create multiple device-files, right? One for keyboard events, and another one for mouse-events. If not, then we need to do some tinkering.

The `RESET` button doesn't emit any events to the OS, so KMonad will not even realize that you've pressed it. It will disconnect the keyboard, so KMonad will stop working as well.

I have no idea about `MIDI`, you might have to do a bit of research yourself there, but if you have more detailed questions about KMonad I'd be happy to answer them.

**Comment by molleweide** [comment]
Thanks for taking your time to answer again.

I believe that you answered just what I needed.
You see, my other qmk layers, none of them are supposed to
send regular keycodes so it should never be possible
to interfere with kmonad from how I understand it.

Qmk keyboards have midi capabilities so I just send midi
notes from the keyboard to Reaper DAW, or any daw.

I am also going o have to read this answer a couple of
times and line it up with the user manual because it is
still a lot of concepts that are quite new to me.

i'm reading this book btw. im starting to get the basics
now. haskell is like black magic
http://learnyouahaskell.com/higher-order-functions

**Comment by molleweide** [comment]
> The only danger is if you switch your keyboard by QMK to a different layout, it will no longer line up with what you specified in kmonad, so the _geometric_ correspondence between your config and the kmonad map no longer lines up

Do you mean like if I get a different keyboard? Then I would only have to create a corresponding 
.kbd file right? macbook.kbd, ez.kbd, dactyl.kbd etc.. And then duplicate the config file and conform it to the new keyboard.
Oh by the way it would be nice if you could create some kind of modular configs so that if I have three different keyboards and the same layout on all i don't need multiple config layers. I could just specify how the surrounding elements differ for each keyboard and then use the same layer definition files for all keyboards. Anyways That thought just popped up in my head. Because I recall you made an issue about config ideas.

**Comment by molleweide** [comment]
I will get back after I tried it. It is going to take a while to test this for me so I that's why I wanted to make sure that the idea makes sense. If it works I will make a more specific and detailed write up of my setup so that you can see how this goes together with my kmonad keymap.

**Comment by david-janssen** [comment]
> Oh by the way it would be nice if you could create some kind of modular configs so that if I have three different keyboards and the same layout on all i don't need multiple config layers.

Yeah, that would be cool :)

**Comment by molleweide** [comment]
yo it turned out to work perfectly. 
only two keys that map incorrectly.
I'm going to make a write up of my setup now and the two keys that don't work so that it becomes easy for you to see and give feedback.

**Comment by molleweide** [comment]
# MY SETUP

I will try to edit this post if I come up with a more clear and concise
description. In essence, only two keys are mapped incorrectly or something wierd
is happening.

## QMK

This link shows the QMK keymap that I am using
https://github.com/molleweide/qmk_keymap_ergodox_ez/blob/7e6c1f9cfc32f23ae556555576a62b7d42be1746/layers/kmonad-mult.h

## KMONAD

This is the link to my ergodox ez kmonad config used within
qmk as a sublayout.
https://github.com/molleweide/kmonad/blob/lazy-button/keymap/user/molleweide/ez.kbd

## WHAT ISN'T WORKING:

Left and right thumb's tab/enter keys are not being mapped
correctly. This manifests as follows:

1. My kmonad outer thumb keys pass through the underlying 
    qmk base layer keycodes
    
    - `@lt`     -> yields `KC_LCMD` from qmk `_BASE` but expects `tab`
    - `@rt`     -> yields `KC_LCMD` from qmk `_BASE` but expects `ret`

2. The QMK outer left and right tab/return fall through
    even though these are set to XX in the `on` layer

    - `XX`     -> yields `KC_TAB` from qmk `_BASE` but expects `XX`
    - `XX`     -> yields `KC_RET` from qmk `_BASE` but expects `XX`

This only happens to the thumb keys in kmonad. Everything 
else seems to work perfectly. If I switch to kmonad `symbols`
or `spacelayer`, then both return and tab works as expected.
So it seems something is happening with my outer kmonad thumb keys.

And to be clear, with kmonad thumb keys I mean the inner subset layout
that I have dedicated to kmonad.

This is what kmonad debug shows:

The <met> key is the `@lt` in kmonad base layer that should send
`tab` and <tab> is the left outer key that is mapped to `XX` in kmonad
base layer.

```
--------------------------------------------------------------------------------
Received event: Press <met>
Running hooks
Registering untimed hook: 94

--------------------------------------------------------------------------------
Received event: Release <met>
Running hooks

--------------------------------------------------------------------------------
Received event: Press <tab>
Running hooks
Block level set to: 1
Registering untimed hook: 96
Registering 500ms hook: 95

--------------------------------------------------------------------------------
Received event: Release <tab>
Running hooks
Emitting: Press <tab>
Unblocking input stream, no stored events
Emitting: Release <tab>
        Tried cancelling expired hook: 95
```

**Comment by david-janssen** [comment]
Ok, let me see. I think this is not actually a bug, but you not being entirely clear on what KMonad is doing, so I think we could basically fix this issue simple with a few little changes in your config.

First of all, you mention `@lt` but it occurs nowhere in your map, so I'm going to assume you meant `@tb` whereever I encounter that name.

### Issue 1
> My kmonad base layer outer thumb keys pass through the underlyingqmk base layer keycodes
>
> - @lt -> yields KC_LCMD from qmk _BASE but expects tab
> - @rt -> yields KC_LCMD from qmk _BASE but expects ret

So, the 4th button on the bottom (full) row of your QMK config is set to: `KC_LCMD`. So, whenever you push it, QMK sends a key-event with a LCMD to `kmonad`. Looking at your `defsrc` block in `kmonad`, you've set the 4th button on the bottom row to `tab`. I think you're trying to make that button 'work' as a tab, but that's not how to do that.

So: the `defsrc` block doesn't really specify anything, it just lines up all the layers in your config with input keycodes that should trigger it. So `@tb` occurs in the same location as `tab` in your `defsrc`, so when we get sent a `tab` by your input keyboard, we're going to trigger `@tb`. Except that physical button doesn't send tabs, it sends `left-controls`.

The same story is true `@rt`. Although looking at it now, this complicates things, because the QMK keycode sent by pushing that physical button is *also* `KC_LCMD`. This means `KMonad` will not be able to distinguish between those 2 buttons at all, because both send identical events. Sadly keyboards don't transmit any '4th row, 5th column' style information, just keycodes and press-vs-release states.

So the fix here is: configure QMK so that every key sends a different keycode (we *can* distinguish LCMD from RMCD, which is probably the easiest fix). Then make sure your `defsrc` block lines up *exactly* with what QMK is sending.

### Issue 2
> The QMK outer left and right tab/return fall through even though these are set to XX in the on layer
>
> XX -> yields KC_TAB from qmk _BASE but expects XX
> XX -> yields KC_RET from qmk _BASE but expects XX

Is actually the same issue: 
1st-button-2nd-row yields a `KC_TAB` from QMK, but you're mapping to `-` in your `defsrc`. Which means that all the buttons in your layers in the position `1st-button-2nd-row` will be triggered when you send a `-` to KMonad. 
last-button-3d-row yields a `KC_RET` from QMK, but your `defsrc` is trying to catch a `'`. 

### Conclusion
> If I switch to kmonad symbols or spacelayer, then both return and tab works as expected.

I haven't checked each button by eye, but I'm guessing that the QMK-output corresponds exactly to the `defsrc` block in those regions. 

Note for example as well that you have duplicates in your `defsrc`. This means some of your definitions are going to get lost. Because essentially every entry in `defsrc` gets lined up with its corresponding buttons in the layers, and then these get turned into dictionaries. So if you have 2 entries for, for example, `esc`, probably the first entry is going to get overwritten by the second (but we make no guarantees about ordering, because this is basically not something you should be expressing anyways, we just try to make do with what is provided).

I hope I've explained what is going wrong well enough. Let me know how it goes.

**Comment by molleweide** [comment]
> First of all, you mention `@lt` but it occurs nowhere in your map, so I'm going to assume you meant `@tb` whereever I encounter that name.

YES!! 😄

**Comment by molleweide** [comment]
Dude I think I'm gonna solve it now because I wasn't really clear on how it all works but now it makes sense with your explanation. brb!!

**Comment by molleweide** [comment]
now it works 🥳

**Comment by david-janssen** [comment]
Wahay :cake:

**Comment by molleweide** [comment]
i got it working on my big sur mac also now @thoelze1. Your instructions worked perfectly!!
