### ISSUE TITLE
openFd: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by muralikodali** [kmonad/kmonad#243]
My OS is Arch Linux with kernel version 5.10 and enabled uinput kernel module.
I have built kmonad with stack.
when i tried to start kmonad as user service, it is giving the error as shown below.

```
May 14 17:06:53 sri kernel: input: My KMonad output as /devices/virtual/input/input584
May 14 17:06:53 sri systemd-logind[369]: Failed to open /dev/input/event18: No such device
May 14 17:06:53 sri kmonad[30687]: kmonad: usb-Logitech_USB_Keyboard-event-kbd: openFd: does not exist (No such file or directory)
May 14 17:06:53 sri systemd[810]: kmonad.service: Main process exited, code=exited, status=1/FAILURE

May 14 17:06:53 sri systemd[810]: kmonad.service: Failed with result 'exit-code'.
```

**Comment by vherrmann** [comment]
Did you change the device file and does it exist?

**Comment by muralikodali** [comment]
ls /dev/input/by-id giving following output :

```
usb-Logitech_USB_Keyboard-event-if01
usb-Logitech_USB_Keyboard-event-kbd
usb-Logitech_USB_Optical_Mouse-event-mouse
usb-Logitech_USB_Optical_Mouse-mouse
```

ls /dev/input/by-path giving following output :
```
pci-0000:00:14.0-usb-0:1:1.0-event-kbd
pci-0000:00:14.0-usb-0:1:1.1-event
pci-0000:00:14.0-usb-0:3:1.0-event-mouse
pci-0000:00:14.0-usb-0:3:1.0-mouse
platform-pcspkr-event-spkr
```

I have enabled kernel uinput module and created a file in /etc/modules-load.d/ called uinput with content:
```
uinput
```

I have created a file 90-kmonad.rules in a directory /etc/udev/rules.d with content :
```
KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput"
```

I have created a new user group `uinput` and added `$user` to the uinput group.

I have created a systemd user service file with following content.

```
[Unit]
Description=kmonad keyboard config

[Service]
Restart=always
RestartSec=3
ExecStart=/usr/bin/kmonad /home/xxxx/.config/kmonad/config
Nice=-20

[Install]
WantedBy=default.target
```

my config file, a basic one copied from github sources to check the service, is attached.

[config](https://github.com/kmonad/kmonad/files/6482391/config.txt)

**Comment by david-janssen** [comment]
I see the problem, you didn't specify the full path to your input file. Try replacing:
>  input  (device-file "usb-Logitech_USB_Keyboard-event-kbd")

 With:
>  input  (device-file "/dev/input/by-id/usb-Logitech_USB_Keyboard-event-kbd")

**Comment by muralikodali** [comment]
Thanks for your suggestion.

kmonad as a user service is running well, after making the suggested change.

It's output is follows :  

```
May 15 12:49:27 sri systemd[922]: Started kmonad keyboard config.
May 15 12:49:28 sri kmonad[45475]: Error loading new keyboard description
May 15 12:49:28 sri kmonad[45439]: kmonad: waitForProcess: does not exist (No child processes)
```
What is this "waitForProcess" ?

Can you please suggest some config templates ( English as language ) to start with ?

**Comment by vherrmann** [comment]
> https://github.com/freenode-japanese/info

You probably made a mistake in your config. Run `kmonad --dry-run` to check it.

> Can you please suggest some config templates ( English as language ) to start with ?

There are used configurations in the keymap/user directory.

**Comment by muralikodali** [comment]
I have to hold the assigned key in the default layer to keep another layer activated (numbers layer).
It is very inconvenient to do so. 
How to activate a layer and move between layers ?

**Comment by vherrmann** [comment]
>  How to activate a layer and move between layers ?

You can sort of use `layer-switch`, but I don't think kmonad has a real lock button, like xkb. But this discussion is off-topic (also you should read tutorial.kbd, if you haven't yet, since it describes all existing buttons in great detail). For further configuration questions there is a [discord](https://discord.gg/3tFfWmnahN) and an [irc](https://webchat.freenode.net/).

 If you want to use vou, take a look at [this german website](https://www.maximilian-schillinger.de/konfiguration.html).

Please close this issue, since your problem has been solved.

**Comment by david-janssen** [comment]
Happy to hear you got everything up and running. As @vhermann correctly pointed out: we have many different buttons. You can find all the different ways of dealing with layers here:
https://github.com/kmonad/kmonad/blob/master/keymap/tutorial.kbd#L535-L664

It's a big file, but it highlights all of the different things KMonad can do. Good luck! If different issues arise, I would like to ask you to open a new issue, so that the content of an issues stays reflected in its title :-)

**Comment by muralikodali** [comment]
Thanks for your support
