### ISSUE TITLE
Seperate repository for user layouts

### ISSUE THREAD

**Issue by miffi** [kmonad/kmonad#255]
Now that kmonad has an organization, wouldn't it make more sense for all the user layouts to be in another repository as they are not related to kmonad's development? The repository could be named something like `kmonad/community-layouts`

**Comment by slotThe** [comment]
What would we gain from a change like that?  I think having user configurations in the same repository as the project (and the same directory as the tutorial!) is worth a lot in terms of discoverability

**Comment by miffi** [comment]
Hmm, my thoughts are
- Having a separate repository would be better for organization.
- Developers won't need to clone all the user-layouts to code (though with such a small userbase this is negligible as of now)
- Discoverability isn't that hurt if we link it at the README like the folder is linked right now (I didn't realise that they were in the same directory actually)

**Comment by 6gk** [comment]
I've personally never even looked at the user layout directory, but I have looked at the tutorial.

I'm not really a fan of the user layout organization method honestly, the goal is presumably "these people use kmonad and here is what they use it for, take some inspiration :)", but ideally it would be labelled with the purpose (I'm aware that this isn't easy), so you can quickly copy-paste and have a "good enough" config for some users.

**Comment by david-janssen** [comment]
I've opened up the wiki to public editing. Maybe that would be a good place to keep track of keymap examples?

**Comment by slotThe** [comment]
Since keymaps are basically just large files of code, I don't necessarily think that a wiki is the best place to contain them.  Then again, this way people didn't have to put in pull requests every few months if they update their configs...  GitHub wikis really are publicly editable though, so there is the possibility of a malicious actor modifying the existing configs (though I judge this community to be awesome enough not to do that)

**Comment by david-janssen** [comment]
> Since keymaps are basically just large files of code, I don't necessarily think that a wiki is the best place to contain them.

Hmmm, you have a point there.

> (though I judge this community to be awesome enough not to do that)

Also true, the people who we run into have been extraordinarily lovely. However, whatever is exposed to the internet eventually gets trolled. Basic rule of life :).

So, what would be the best thing to do? User-config repo on the organization? Just leave it as it is? I always enjoyed being able to look through other users' keymaps in QMK, which is why I initially set things up this way.

**Comment by vherrmann** [comment]
Another option would be to link to the repositories of the users somewhere on the readme/wiki/in the repo. So that not *anybody* can change the configs.

**Comment by molleweide** [comment]
Sort of similar to how qmk adds all of the keyboards as submodules i believe

**Comment by MuhammedZakir** [comment]
> What would we gain from a change like that?

Probably not a big issue, but by doing this, we can keep development git log "clean"? This is not an issue atm because of small userbase and few contributions. So IMHO, what we should be discussing is whether to do it now or to do it when there are enough/frequent contributions.

**Comment by david-janssen** [comment]
I think it's probably a good change that I intend to make when we get close to releasing a new version.

**Comment by pataquets** [comment]
Allowing users to edit the wiki only to add a short description plus a link to a Gist with their configurations would strike a nice balance, IMHO. Everyone maintains his/her own snippets (with independent commit logs) and they can be also shared.
Cross-linking to #303, which could be somewhat related with this issue if we want to share snippets instead of full configs.

**Comment by slotThe** [comment]
I'd like to do something about this after all.  So far, the suggested options seem to be 

  1. Create a new repository within the kmonad organisation
  2. The wiki is freely editable, so move everything over there
  3. Have users maintain their own repos/gists with their configurations and link to them in the README
  4. Have users maintain their own repos with their configurations and include them as submodules

Is there a general consensus here in which direction to move in order to inconvenience the smallest numbers of people? :)

**Comment by MuhammedZakir** [comment]
> 1. Create a new repository within kmonad organisation

I think this is needed so that we can have a "checked"/"curated" configs. The problem is mainly because of shell commands. I understand that the users **must** check the config they import, but when checking, especially a big config, it's quite likely to miss these kinds of things. Having a community maintained repo would make checking/maintaining things safer. The additional maintenance overhead can be reduced by giving access to this repo to few people. They can then review/merge PRs. This is what Karabiner does.

**Comment by slotThe** [comment]
I finally got around to this: https://github.com/kmonad/kmonad-community is now live!
