### ISSUE TITLE
[Feature Requests]context aware functionality

### ISSUE THREAD

**Issue by SuJiKiNen** [kmonad/kmonad#265]
hi, I want some functions only activated in certain application or certain circumstance.
layer level:
like when start a game program,it automatic switch to layer qwerty(I mainly use Dvorak) and disable some certain keys(eg. windows key)

alias level:
when default alias ```cpy``` to ```ctrl+c```
in gnome-terminal alias ```cpy``` to ```ctrl+shift+c```

this may also implemented like key sequences translation,
and this may not associated to any layer.

actually this may related to #101,but add if statement, or programmable config.

some other thoughts,sorry for I put this together.
1,I think we can define aliases before key translated
when these keys press no matter what stack is,it only recognized as origin key.
(defprealias toggle-kmonad "ctrl-k-l")
2,`layer-toggle` is confused for me,I comes from `qmk`
I can't be activated and deactivated layer when pressed,It needs hold.
while `layer-switch` can't switch back when press again.
I need two keys if I need switch back default layer.

key sequences processing diagram:
`keys-seqs` =>`pre-key-seqs-cosumming` =>`layer-translation(key-mapping)` => `post-key-seqs-cosumming`

**Comment by slotThe** [comment]
On Sat, May 22 2021 20:47, SuJiKiNen wrote:
> hi, I want some functions only activated in certain application or certain circumstance.
> layer level:
> like when start a game program,it automatic switch to layer qwerty(I
> mainly use Dvorak) and disable some certain keys(eg. windows key)

I believe David declared this "out of scope", as it is really
environment-specific and not the kind of level that kmonad operates at.

**Comment by david-janssen** [comment]
Hey there, 

Thank you for the suggestions. I'm not sure I understand them all completely, but here are my responses:

> hi, I want some functions only activated in certain application or certain circumstance.

So, we're not going to implement "detect the active application" functionality, because that would be a huge headache, and as @slotThe correctly relayed, very much "out of scope". I do intend to implement the ability to send arbitrary signals to kmonad. So you could start kmonad and have it running, then, in another terminal type something like "kmonad send-signal enter-game-mode". Here 'enter-game-mode' would be completely user-defined, and in your config you could bind KMonad actions to that signal.

This way everyone can implement their own OSes detection mechanism, and send 'virtual buttons' to KMonad from scripts, which I think would enable the desired behavior without us having to actually program it. Essentially, we provide you the API or the entry-point, and then you get to do it yourself. :).

> 1,I think we can define aliases before key translated

This suggestion is sounds a lot like key-combos or chords and is indeed something I am thinking about how to implement. Some parts of the model are currently a bit strict, making this really hard to 'just add', but we are brainstorming different ways of organizing the functionality that would make this easier. This is very much a feature I am hoping to add at some point.

> 2,layer-toggle is confused for me,I comes from qmk

I'm really not sure what you mean under this point. You can switch from A to B using a `layer-switch B` in `A`, then you can switch back to `A` by having a `layer-switch A` in your `B` layer. There is no `default` layer, you can set the base-layer to whatever you want. I don't see how your suggestion adds any power that isn't already present.

I hope I've sufficiently understood your suggestions and clarified my intentions. If so: please close the issue. If not, let me know what is still unclear.

**Comment by SuJiKiNen** [comment]
thank you for quick reply.
about `detect the active application`,here is my thought,
this is much like Emacs buffer local variable,every buffer holds its own value.
now every application holds its own config,so the key is to know what  application windows is 
activting now.
`game window activated`  kmonad use game.kbd
`terminal window activated` kmonad use terminal.kbd 
IPC seems tricky,I am ok if this is "out of scope"

about layer switch,sorry,I stuck in qmk,cause I only set toggle key in base layer,
the other layers upon this key just was transparent key.
I think toggle-layer should rename to something indicates temporarily layer
toggle means turn on and off,you need press twice.

**Comment by david-janssen** [comment]
> so the key is to know what application windows is activting now.

Yep, that is the real hangup, because not only is it not straightforward, it is *different* for Windows, Mac, Linux. And then probably different for `X11` vs `Wayland`, different for `Windows7, 8, 10`, maybe different for `OSX` vs `OS11`. That's why it's a huge headache and out-of-scope :D

> toggle means turn on and off

You are absolutely right. I hadn't considered it, but semantically the word `toggle` can be confusing here. Maybe `set-base-layer` or `switch-to-layer`?

**Comment by SuJiKiNen** [comment]
we don't need to reinvent the wheel,do a quick search and found [this](https://github.com/ActivityWatch/aw-watcher-window)

renaming may break user's config,for compatibility,how about declaring a version string in config file,if current function version not match current kmonad,warning user to upgrade kmonad.

I think `hold-to-layer` which more straightforward.
`set-base-layer` and `switch-to-layer` does not tell that user release the key will fall back to base layer.
`set` and `switch to` will result a persist state.

**Comment by david-janssen** [comment]
> we don't need to reinvent the wheel,do a quick search and found this

Hey, that is a cool project. That'll make it really easy to send signals to KMonad when we implement the signal-functionality. I should remeber to include this in the documentation at that point.

> I think hold-to-layer which more straightforward.

Heh, you got me confused about my own names and I mixed them up in my head when I was writing my reply.

`layer-toggle` toggles on a layer when pressed, and then removes it when released, so `toggle` actually does fit relatively well. Maybe `layer-while-held` would be even clearer? 

Not going to make this change now, because I don't want to break backward compatibility, but I'll give the names another good think when we are getting ready for a major version change, because then I'll be happy to break backward-compat.

Going to close this now, because we have another issue for the KMonad signals already up somewhere, so this issue is not actionable, but I'll still be replying in this thread.
