### ISSUE TITLE
Possible to add delay to multi-use key playback?

### ISSUE THREAD

**Issue by Liquidmantis** [kmonad/kmonad#271]
This might be something of a corner case, but I have an issue where the tap-next-release queued playback is too quick.  I'm wondering if it's possible to add a micro delay between the hold-behavior key and the buffered modified key.

My use case is that I have `ehy (tap-next-release esc f17)` bound to caps.  F17 is configured in Hammerspoon to trigger my hyper mode, which has a set of hotkeys for Yabai, the tiling window manager I used on Mac.  In reviewing the debug output from kmonad and Hammerspoon, I can see `<f17><l>` get played back, which should focus the window to the east, but Hammerspoon is only catching the <f17> press to trigger my Hyper mode and doesn't catch the `<l>`.  I can hold `<esc>` and double-tap `<l>`, which works fine as it triggers the hold behavior in kmonad and sends `<f17>`, and then Hammerspoon can catch the second `<l>`.  If I could add a micro delay before kmonad emits the `<l>` (or any other hotkey) that would solve this issue without requiring the double-keying.

For now I can get things working with `ehy (tap-hold-next-release 130 esc f17)` but that has the same problem if I type too quickly.  If I lower the hold timer any more than that I start getting into false-hold timing issues.

I only just got kmonad working yesterday, after learning it was a solution to recreate my Moonlander's QMK layout on my other laptops' built-in keyboard, so if there's another solution here, macros or something, feel free to suggest better solutions.  I'll probably look into a multi-tap binding today but I would love to have the same behavior as my QMK config.

Thanks for the great project!

**Comment by MuhammedZakir** [comment]
Just wondering: is it possible to add `delay` to `key`s rather than functions? That is, something like`P(key ms)`, which would add a delay after that `key` is emitted and the next event will be done only after that delay. Similar to `pause` in `tap-macro`, but a more general one which can be used in all other functions.

**Comment by Vermoot** [comment]
You can make use of `tap-macro` to add a delay to your button, something like `(defalias ehy (tap-next-release esc (tap-macro (pause 50) f17)))` should work. I think.

**Comment by MuhammedZakir** [comment]
> You can make use of `tap-macro` to add a delay to your button, something like `(defalias ehy (tap-next-release esc (tap-macro (pause 50) f17)))` should work. I think.

`(pause 50)` should be after `f17`. Also, you can use `Px` notation for `pause`:

```
(tap-macro f17 P50)
```

**Comment by Liquidmantis** [comment]
Thanks for the suggestions and the testing!  I'm not having any luck with it for my uses because I'm really using F17 as a modifier.  I do this so I can also use shift, ctrl, and/or alt in conjunction with it, compared to a traditional Hyper key comprised of all the modifiers.  So the issue for me is that with the pause before F17 means the playback is still the same timing, and Hammerspoon doesn't have time to switch modes and catch the action key.  But with the pause after F17 the mode is triggered and released before the action key.  I need PF17, pause, P`<actionKey>`, R`<actionKey>`, RF17.  I could try adding a delay in Hammerspoon, so that it holds the mode open for a micro delay on keyUp but I'd rather not.  I think a multi-tap solution is likely the only answer.

**Comment by Vermoot** [comment]
Using a non-mod key as a modifier is always a bit tricky.

One thing I've seen mentioned is the idea to have a "right hyper" key, meaning a hyper key using the right set of modifier. That way you can still use cmd, alt, ctrl and shift in addition to it. I've just started an issue on skhd's github to add that, because that's something I'd like to use too.

Another "solution" would be to use `fn` instead of `hyper`. This is definitely possible with kmonad, and I've done it in the past, but if the goal is to recreate your QMK layout, that can be an issue since using macOS's `fn` key in a QMK keymap can be a little iffy. Definitely possible though, ask on QMK's discord, iirc there's a patch going around that allows you to use the `KC_APFN` keycode (iirc), created by fauxpas (very active helper on the discord, and contributor on qmk's github.

Besides those workarounds, I'm not sure how you can make your `F17` thing work. I've been in the same boat, and for now I've gone back to using hyper, and not using any hyper+mod combination. I have hyper on capslock, and `meh` on tab, for a bit more versatility, but I'd love to be able to use hyper with mods. Maybe if skhd adds `rhyper`, then we'll see.

**Comment by Liquidmantis** [comment]
Thanks for all the feedback!  I haven't spent a lot of time using it yet, but just using `tap-hold-next-release` with a relatively tight hold timeout is working reasonably well for me.  I just need to to be more deliberate with the timing of my keystrokes.

I've considered trying to use the right modifier keys to define my hyper key like you say, it's just the hidden function keys are such a juicy target for a non-conflicting input that gives you so many potential modifier options.  It's not the first time that drafting it into being a pseudo-modifier key has caused some special case handling though.

One thing I'm realizing with this attempt, as well as using homerow mods, is that I use rolls _a lot_.  This works fine with traditional modifier keys, and Karabiner[-Elements]'s rebinding of caps to esc/ctrl works great, at least now.  I seem to recall it having some issues in Elements' early days.

Before diving into the QMK and now kmonad rabbit hole I was using my left control for my F17 hyper and that worked well, but now that I've seen how comfortable homerow mods are, and I can move my caps-based ctrl over to my `<a>` key, I think I'll just need to work on my typing precision to make my keypresses more deliberate and distinct.  We'll see how that holds up during "automatic" typing and at speed rather than in my mindful configuration testing.

**Comment by Vermoot** [comment]
Sadly Karabiner still doesn't allow the use of home row mods. As far as I can tell (and let me tell you I've spent time on this), there isn't anything resembling QMK's `IGNORE_MOD_TAP_INTERRUPT`, which is crucial for them. kmonad does it really well though, so we can be thankful for that.

Home row mods do take a bit of getting used to, you need to both tune the timings to what you need them to be, and train your muscle memory to use them just right, and sometimes one interferes with the other so it can take a bit of time, but IMO it's *definitely* worth it.
