### ISSUE TITLE
Can key auto-repeat be implemented inside KMonad?

### ISSUE THREAD

**Issue by MuhammedZakir** [kmonad/kmonad#290]
OS: Manjaro (KDE Plasma - X11)

Edit: Can key auto-repeat be implemented inside KMonad? Currently, KMonad is unusable inside virtual terminal because of no auto-repeat.

**Comment by 6gk** [comment]
I don't think this is an issue with KMonad.  
KMonad makes a new input device, and xset doesn't apply to ones added after the command was ran.

To test this, run your `xset r..` command then unplug/replug your keyboard.

**Comment by 6gk** [comment]
What I have in my config is:

```
output (uinput-sink "kmonad-input" "sleep 2; xset r rate 200 60; xset -r 192; xset -r 127")
```

(I don't want repeat on f14 & pause, hence the -r [num])

**Comment by MuhammedZakir** [comment]
Thanks for the info! :-)

**Comment by migueldeoleiros** [comment]
OS: Arch Linux 5.14.15 
I'm not sure if this is the right place to ask this, but I can't use kmonad on tty because it disables keyboard autorepeat. I assume this is beacuse it needs xset and that needs and Xsession running. 
I just want to be able to run kmonad on my loging tty as I sometimes just work from there instead or running a graphical session.
Is there any way I could archieve that? everything else works as expected.

**Comment by 6gk** [comment]
My thing about needing xset was because the original issue was about it breaking xset.

KMonad doesn't natively support repeating, but X users will be using xset anyway.

Also, bit late but @MuhammedZakir It's generally bad practice to repurpose issues instead of making a new one -- you created this one because it broke xset, then you repurposed it to be for native repeating, which just causes confusion (see above comment) & makes it less likely for devs to see the request.

**Comment by mauedu** [comment]
This sounds very similar to #188. 
I'm not sure if it's relatable at all but key auto-repeat has been implemented for Windows in the `keycode-refactor` branch. It's controlled via the `defcfg` block. In Windows it's on by default with default values, but maybe in Linux it could be off by default with optional parameters? Related windows issue: #82. Here is the commit that added it to Windows: 07b062c96078b3353f6a60317a3c0d5253680b6b

**Comment by MuhammedZakir** [comment]
Native key-repeat is implemented in `keycode-refactor` branch/PR.

---

> Also, bit late but @MuhammedZakir It's generally bad practice to repurpose issues instead of making a new one -- you created this one because it broke xset, then you repurposed it to be for native repeating, which just causes confusion (see above comment) & makes it less likely for devs to see the request.

I will keep that in mind. :-)

**Comment by ChoppinBlockParty** [comment]
> Native key-repeat is implemented in `keycode-refactor` branch/PR.
> 
> Edit:
> 
> To adjust key-repeat, add a tuple in `output`: `output (uinput-sink "KMonad Keyboard" "" (300,100))`. Here, `300` is delay before repeating, and `100` is interval between repeating events. Default is `(300,100)`.

In kmonad 0.4.2 this does not work for me on Ubuntu 22.

> output (uinput-sink "kmonad-input" "sleep 2; xset r rate 200 60; xset -r 192; xset -r 127")

Surprisingly neither is this one. Can it be related that I run kmonad as root from systemd?

**Comment by jtroo** [comment]
KMonad should have key repeat in a desktop environment but I believe does not support repeat in console-only environments today.
