### ISSUE TITLE
Alternative NixOS module

### ISSUE THREAD

**Issue by pjones** [kmonad/kmonad#306]
First, and most importantly: thank you to everyone that has contributed time to such a neat project.

While adding KMonad to my NixOS configuration I ran into a couple of problems.  The biggest was that the existing NixOS module doesn't allow a KMonad configuration file that is generated and placed in the Nix store.  Due to all the string manipulation on the path by the module, Nix rejects the systemd config because it refers to out paths.

I [took a different approach](https://github.com/pjones/tilde/blob/1f0ca7720fed03490993e2a92294263f10e1ee77/nixos/workstation/kmonad.nix) that I thought others may be interested in.  I haven't opened a pull request because my NixOS module isn't backwards compatible with the existing one in this repo.  Mine differs in the following ways:

  * Keyboard configuration is generated by the module on the fly and tested with `kmonad -d`.
  * The service is started via `systemd.paths` when the device file appears eliminating the need for "optional" configs
  * The service doesn't need a graphical environment and works on the console.
  * `kmonad` runs as an unprivileged user.

 If anyone wants to retrofit the existing module I'm happy to help.

**Comment by slotThe** [comment]
> I haven't opened a pull request because my NixOS module isn't backwards compatible with the existing one in this repo. 

I don't think we need to worry much about backwards compatibility at this point.  The nix module in the [latest release](https://github.com/kmonad/kmonad/tree/0.4.1/nix) is quite different from what we have now (and afaik also incompatible), so I'd say that if you feel like preparing a pr definitely go for it!

Especially since most of 

>     * Keyboard configuration is generated by the module on the fly and tested with `kmonad -d`.
> 
>     * The service is started via `systemd.paths` when the device file appears eliminating the need for "optional" configs
> 
>     * The service doesn't need a graphical environment and works on the console.
> 
>     * `kmonad` runs as an unprivileged user.

sounds like a straight upgrade from what we have now (especially the last two points)

**Comment by ajgrf** [comment]
I don't agree with generating the `defcfg` section, because it means my kbd file would no longer transfer perfectly to other distros. Most of the options in `defcfg` have corresponding command line arguments anyway, so that might be a better way to set them from a nix module (as optional overrides of the config file).

Everything else looks like a strict upgrade to me. I don't mind the compatibility break, but there's also changes to the NixOS module happening in #289.

**Comment by pnotequalnp** [comment]
> The service doesn't need a graphical environment and works on the console.

The older NixOS module on my open PR #289 also works in a tty. Was there a regression on master since then that changed this?

> `kmonad` runs as an unprivileged user.

Does this mean it would be possible to create a Home Manager module instead of NixOS? I'm still not familiar with the low-level mechanical details of how it handles inputs.

On the topic of generating the `defcfg`, writing a module to do this was on my todo list. The idea being that I want the same layers on multiple machines, but the `defcfg` itself is machine-dependent since it encodes information like the OS and the keyboard's device file.

**Comment by gilescope** [comment]
An alternative would be great because the existing one is broken.

**Comment by slotThe** [comment]
@pjones any updates on this?  As I said, I would be fine with a breaking change (as the `keycode-refactor` branch will definitely have them as well anyways)

**Comment by pjones** [comment]
@slotThe I'm not really sure how to proceed on this.

I have a working NixOS module (link in the issue description).  However, based on the comments in this issue, it's not clear what parts of it would need to be changed.

I suppose I could just drop it into a PR as-is and go from there.  Does that sound good?

@pnotequalnp I don't think this could work as a Home Manager module.  It needs to create a `kmonad` user and some udev rules.

**Comment by eighal** [comment]
Sounds good to me, FWIW

**Comment by slotThe** [comment]
@pjones 

> I suppose I could just drop it into a PR as-is and go from there. Does that sound good? 

Sounds good to me!

**Comment by david-janssen** [comment]
Since I have been out of the loop for a while I am just popping in here to say that we seem to be ready to pull the trigger on this. I feel a little bit hesitant to pop up out Lethe and start merging changes, so... Any objections to merging this in?

**Comment by pjones** [comment]
The new NixOS module is almost stable.  There's only one thing left that I want to add...

For people like @ajgrf who don't want to have to remove the `defcfg` block, I want to add the ability to pass the device file on the command line instead.  Since that's the least intrusive path, I'm also going to make it the default.  Generating the `defcfg` block will be an option you can enable if desired.

**Comment by jottr** [comment]
@pjones are you still planning to create a PR for this?

**Comment by pjones** [comment]
@jottr The new NixOS module was merged 2 years ago.  I should have closed this issue.  Sorry.
