### ISSUE TITLE
Shouldn't the logo of the organization be changed?

### ISSUE THREAD

**Issue by salahdin-ahmed** [kmonad/kmonad#309]
Hello,

I noticed that the logo of the organization kmonad still did not change, it still have the default empty logo. I think the KM in the main logo of the software should be the logo of the organization or even the whole logo. Anyway, I think it should be changed since the software already have a logo.

Thanks for the time.

**Comment by 6gk** [comment]
David seems to be a tad inactive [not uncommon btw] atm and I don't think anyone else has the appropriate permissions so that's probably why it hasn't been done.

![discord screenshot](https://user-images.githubusercontent.com/40295114/125438955-04b78547-5107-45ae-b6b7-3856c1eb72de.png)

[transparent logo image is here](https://user-images.githubusercontent.com/40295114/119228666-6a9aa280-bb57-11eb-957d-b817c774020f.png)

**Comment by MySurmise** [comment]
No, the current Logo is the better one, because it is oversimplified.

(Context: https://www.youtube.com/watch?v=LoYP2mEJDJs )

**Comment by 6gk** [comment]
Sorry, what?  @MySurmise

[this is the current org logo - the default github one.](https://user-images.githubusercontent.com/40295114/126038474-1baaf097-6162-4259-9864-9355a1877d54.png)

[this is the actual logo, which the org is yet to change to](https://user-images.githubusercontent.com/40295114/119228666-6a9aa280-bb57-11eb-957d-b817c774020f.png)

**Comment by 6gk** [comment]
@david-janssen Reminder of this issue. ​ Not urgent, of course, I just remembered it.

**Comment by david-janssen** [comment]
Wahay, it is done. Thanks for the reminder.

**Comment by 6gk** [comment]
Nice!  :+1:
