### ISSUE TITLE
[question] Input system/Switch keyboard language?

### ISSUE THREAD

**Issue by hermann-p** [kmonad/kmonad#331]
My current situation is that I'm using an extended mechanical keyboard with US-layout to work and use a custom Plasma keybinding to switch the layout to German for chatting with my coworkers.

My goal is to have or emulate that behaviour when using other window managers, so is there a feasible way of changing the input language completely, apart from writing a language-specific layout for every modifier key?

In an x-session I could just bind `setxkbmap ...` to any key, but what about wayland-compositors which read the kbd only once on startup?

How would KMonad behave if I call `setxkbmap` while it's running, anyway? Does it receive raw key events or those translated by the X-server?

EDIT: I didn't try setting the xkbmap while under Plasma, as it also has some keyboard management hooked before it. Changing language via Plasma settings is reflected in KMonad, e.g. z becomes y after I switch to the US layout.

**Comment by iaeerfung** [comment]
Wm's have tools to feed/change configuration on-the-fly (swaymsg, i3-rpc).
If your active layer matches qwerty -- all external keybinding tools (even plover steno and chinese input engine) will work as expected, kmonad is very low-level.

**Comment by vherrmann** [comment]
- kmonad processes keycodes, not keysymbols, so you don't have to change your layers if the position is important, not the symbol (the text on the keys of your keyboard)
- wayland compositors have their own way of changing the keyboard layout, so you won't be able to use a uniform `setxkbmap` or sth
- there is no problem with running setxkbmap, while running kmonad, kmonad processes the keys before X. (Though you may want to use a different mapping for qwertz).

PS: In case you use qwerty for its better symbols instead of simple qwertz, i can recommend you one of the successors of the neo keyboard layot (https://neo-layout.org/, http://www.adnw.de/index.php?n=Main.HomePage, https://www.maximilian-schillinger.de/keyboard-layouts-neo-adnw-koy.html)

**Comment by hermann-p** [comment]
Thanks for the clarification. After the explanation it was clear I could use a hybrid -- use xkb-tools to set the WM's layout to `us,de` with a switch-layout-key managed directly by xkb, and using KMonad to get those special behaviours like mapping `[home]` to `[capslock]` for my emacs leader keys (doom with evil disabled and replaced by a customised xah-fly-keys map).  
It's a pity there's no way to distinguish between the multiple `[control]` and `[backspace]` keys on my [x-bows keyboard](https://x-bows.com/) in a more granulated manner, but that's due to them all sending the same keycode.  

@vherrmann, the person having my first name as a last name ;) -- thanks for pointing out the neo-... keymaps. They are somewhat intriguing, but would also force me to learn typing anew. I might if I find the time. My main reason for switching to US was not better symbols in the first place, but I my boss ordered me the x-bows keyboard and it would need one more key for a German layout (the one just next to the left shift) -- and having no `|` in the shell or no `<>` in React is kind of a bummer... I noticed only afterward that it saved me from rolling the thumb under my hand to type angular parantheses for example...

**Comment by vherrmann** [comment]
@hermann-p If you have the time someday and want to use neo, simply join the #neo irc, we can help you with using one of the neo-family with x-bows

PS: Please close the issue, as far as i see, all your questions were answered
