### ISSUE TITLE
Question or feature: How to use kmonad to remap keys on the remote Linux serve?

### ISSUE THREAD

**Issue by tainzhi** [kmonad/kmonad#336]
I use xrdp to link to the remote ubuntu system through  Windows Remote Desktop Connection. 
No input device found by `evtest`. 
How to configure xinput virutal keyboard as the input device?

**Comment by slotThe** [comment]
On Wed, Aug 18 2021 18:56, QFQ wrote:
> I use xrdp to link to the remote ubuntu system through  Windows Remote Desktop Connection. 
> No input device found by `evtest`. 
> How to configure xinput virutal keyboard as the input device?

So you have a remote connection Windows -> GNU/Linux and want to use
kmonad on the latter, but not the former?  I don't think this is
possible, as xrdp just tells the X server about the keys you pressed,
but we interact with the kernel directly instead of going through X.

**Comment by tainzhi** [comment]
Thank you for your kind reply. 
Kmonad is a great tool for remapping keys. 
It seems that I need to find other ways to change keys while using xrdp.

**Comment by slotThe** [comment]
On Wed, Aug 18 2021 22:52, QFQ wrote:
> It seems that I need to find other ways to change keys while using
> xrdp.

Depending on how much access you have to the remote machine, you could
perhaps try to create an xmodmap config file

**Comment by tainzhi** [comment]
Thank you for your suggestion, I will search Google to find some intros to create an xmodmap config file.
