### ISSUE TITLE
Help macOS Catalina

### ISSUE THREAD

**Issue by DanielCardonaRojas** [kmonad/kmonad#391]
I'm trying to get kmonad working on Catalina but I'm getting this: 

![image](https://user-images.githubusercontent.com/5472687/139756394-e2a60bc6-110a-4632-8a86-105d2168084d.png)

Any ideas? this is with dext a setup.

**Comment by MuhammedZakir** [comment]
Is Karabiner-Elements running? If so, you will have to disable input modification for the devices you want to modify using KMonad.

`connect_failed asio.system:2` is most probably due to incompatible dext. See `Installing the dext` section in `doc/installation.md`.

**Comment by DanielCardonaRojas** [comment]
Quitting karabiner elements did remove the log message related to exclusive access. Looks like its reading keystrokes but a still get continious log message saying: `connect_failed asio.system: 2`. 

What is the meaning of this ?

**Comment by MuhammedZakir** [comment]
You only need to turn turn off input modification in `Devices` tab in Karabiner-Elements preferences. You don't need to quit the app.

---

Re: `connect_failed asio.system:2` is most probably due to incompatible dext. See `Installing the dext` section in `doc/installation.md`. You can find compatible dext version and how to install them in that section.

**Comment by DanielCardonaRojas** [comment]
Thanks I got it working and even added a start up script. Feel free to close this.
