### ISSUE TITLE
`cmd-button` call yabai win manager returns `yabai-msg: failed to connect to socket..`

### ISSUE THREAD

**Issue by molleweide** [kmonad/kmonad#423]
### Discussed in https://github.com/kmonad/kmonad/discussions/422

<div type='discussions-op-text'>

<sup>Originally posted by **molleweide** November 16, 2021</sup>
I am going to try to create a dedicated layer for hosting my window manager commands.
I am using yabai on macos. I will report back if it works or doesn't :P</div>

**Comment by molleweide** [comment]
I have tested running yabai window manager commands with `cmd-button` from kmonad and it returns a socket fail:
```shell
╰ kmor
Password:
connected
yabai-msg: failed to connect to socket..
yabai-msg: failed to connect to socket..
yabai-msg: failed to connect to socket..
yabai-msg: failed to connect to socket..
yabai-msg: failed to connect to socket..
yabai-msg: failed to connect to socket..
```
I'm guessing that this is an issue pertaining to kmonad right? and not to yabai in this case.

**Comment by molleweide** [comment]
i am going to test creating an external script and call this script from kmonad and see if it works.

**Comment by molleweide** [comment]
It turns out calling a bash script that in turn calls yabai also returns socket error. The exact same error.

**Comment by molleweide** [comment]
if I pgrep for yabai in the bash scripts it returns this:
```shell
╰ kmonad
Password:
connected
5802
0
yabai-msg: failed to connect to socket..
5802
0
yabai-msg: failed to connect to socket..
```

**Comment by molleweide** [comment]
I have talked to some people at yabai and they don't understand why this happens so this most likely has something todo
with kmonad's command execution.

**Comment by MuhammedZakir** [comment]
I found the problem. Shell commands are run by `root` and I think either you can't run `yabai` commands as `root` or `yabai` expects commands from the same user who started it.

Opened an issue: #426.

**Comment by molleweide** [comment]
only using this did not works:
`  T34 (cmd-button "sudo zsh -c \'yabai -m space --layout stack\'")`

**Comment by MuhammedZakir** [comment]
> question where do I put th `su user` command? do I prefix every command with `su user; yabai something...`?

Executing once is enough. That will put you in the default shell of that user and that shell will be run as `<user>`. It's like running shell inside another shell, but the "inner" shell is run as another user.

> Also, if I run `sudo zsh -c \'yabai -m space --layout bsp\'` alone, how should I interpret this? Is sudo reaching outside of root into user? Because `sudo` is making it root again right?

I mentioned this because you can't run `yabai` using `sudo`. If you execute `sudo yabai`, it will exit with an error message saying you can't run using `sudo`. Using `sudo zsh -c ...`, `zsh` is the one that's being executed as sudo and `yabai` will run as `root`.

> And I am assuming that you mean I can ommit `su <user>` if I run `sudo zsh -c ....`

Yes.

---



> only using this did not works:
> ` T34 (cmd-button "sudo zsh -c \'yabai -m space --layout stack\'")`

That won't work. What you are doing is running `yabai` as `root` which is what we want to avoid. To make it work, we will have to run `yabai` as the current user. That is possible using `sudo -u` or `su`, but it's better to wait for the fix.

**Comment by molleweide** [comment]
ok I'll wait for the fix. I'm super excited about this!! This is going to be so cool when it is fixed.

**Comment by slotThe** [comment]
I guess we have #426 now to track this
