### ISSUE TITLE
Crash on multiple layer-next calls

### ISSUE THREAD

**Issue by canadaduane** [kmonad/kmonad#425]
With the following kbd config, pressing `C-a` three times crashes kmonad:

```
(defcfg
  input  (device-file "/dev/input/by-path/platform-i8042-serio-0-event-kbd")
  output (uinput-sink "kmonad virtual keyboard")
  fallthrough true
)

(defsrc lsft lctl a)

(defalias
  boom C-(layer-toggle boomed)
  a (around S-a (layer-next boomed))
)

(deflayer initial lsft @boom a)

(deflayer boomed lsft lctl @a)
```

Here's the output at the end (I think this is a crash?):
```
$ sleep 1; sudo /usr/local/bin/kmonad /etc/kmonad/layer-toggle-crash.kbd -ldebug
... [snip] ...
Received event: Press <a>
Running hooks
Registering untimed hook: 13
Registering untimed hook: 15
Emitting: Press <a>
Registering 0ms hook: 14
Cancelling hook: 14
Closing process: emitter_proc
Closing KeySource
Releasing ioctl grab
^AClosing KeySink
Unregistering Uinput device
Closing Uinput device file
kmonad: LayerNotOnStack "boomed"
$
```

**Comment by slotThe** [comment]
On Tue, Nov 16 2021 21:35, Duane Johnson wrote:
> With the following kbd config, pressing `C-a` three times crashes
> kmonad:

This is because when a layer is already on the stack of layers, we don't
add a second copy onto it or anything, we just promote it to the front.
If I didn't mess up, the series of keypresses then go a bit like this:

  1. PC -> Go to layer `boomed` for as long as we don't hear from a RC
           event.
  2. Ta -> Promote `boomed` to the front for the next press.
  3. Ta -> This is the next press after 2., so do it in the layer
           `boomed`.  What do we do?  We promote `boomed` to the front
           (it still is) for the next press.  Once we let go of this
           key, the release condition of 2. hits and we pop `boomed`.
           We now only have the base layer on the stack.
  4. Ta -> This is the next press after 3., so do it in the layer
           `boomed`.  This is where I believe a race condition occurs.
           While we do press the key, we do not have enough time to push
           `boomed` to the stack.  Instead, the popping action of
           3. takes precedence but, since `boomed` is already popped,
           there is no such layer on the stack.

All that is to say `layer-next` is quite ghastly :).  Now, the good news
is that this is already fixed in `master`—we now simply emit a log
message that a non-existent layer is supposed to be popped and fall back
to the default layer (which is quite sane behaviour, I think).

**Comment by slotThe** [comment]
I will close this because it's fixed in master—feel free to get back with more questions though :)
