### ISSUE TITLE
Use Haskell official Docker image as base in Dockerfile

### ISSUE THREAD

**Issue by pataquets** [kmonad/kmonad#479]
The current Dockerfile uses `lierdakil/alpine-haskell:8.10.4` as base image.

This has some drawbacks compared with the [official Haskell image](https://hub.docker.com/_/haskell):
* It has only AMD64 arch. No ARM arch images available (issue #261 could be addressed).
* It is not audited for security vulnerabilities (check [tags](https://hub.docker.com/_/haskell?tab=tags)).
* It has no `:8` nor `:8.10` tags to automatically build with latest 8.x/8.10.x minor/patch versions. This makes harder to track latest versions (as of now, we are using 8.10.4, as opposed to 8.10.7 from the `haskell:8` tag).
* Although [source is available](https://github.com/lierdakil/alpine-haskell), it is not an [Automated Build](https://docs.docker.com/docker-hub/builds/), which lacks traceability/auditability on the build process & artifact contents.
* It lacks the wider Haskell community usage and support.

It would imply switching from Alpine to Debian (musl to glibc), which I'm not sure wheter it's good or bad, since I can't fully grasp the implications. Size is not a concern, since image is not meant for distribution.

AFAICT it would only be a matter of copying the base image's Dockerfile steps into kmonad's Dockerfile (I can volunteer, but I'm no Haskell programmer and I can't understand the build process).

Requesting for feedback whether it makes sense or not.
cc @lierdakil

**Comment by lierdakil** [comment]
> It has no :8 nor :8.10 tags to automatically build with latest 8.x/8.10.x minor/patch versions.

The project is built with stack. Stack resolver pins GHC versions. So silent upgrades on CI _will_ break stuff. You _don't_ want silent compiler upgrades.

> It is not audited for security vulnerabilities

Arguably, security considerations beyond a modified compiler are irrelevant for an image that runs for half an hour once in a while on a public CI instance.

> It lacks the wider Haskell community usage and support.

Very much so, the bus factor for these images is unbelievably low. However, the dockerfiles are public, and I think those are straightforward enough for anyone to be able to pick this up if necessary.

>  it is not an Automated Build

Because Docker hub's free-tier automated build straight up times out halfway through. I could probably hack something together with github actions (which have much more generous build time limits), but I can't justify the time investment required. PRs welcome, as usual.

> It would imply switching from Alpine to Debian (musl to glibc)

The point was very much to avoid that -- static builds are impossible with glibc.

You could just do what my docker image does on the alpine image manually (it's not like it does much). However, setting up GHC  can take _a while_ (hence it's a docker image and not a script), so builds will take a lot longer. You could try caching, I guess, but IMO that's trying to solve a non-issue.

**Comment by slotThe** [comment]
This answer convinces me (especially the musl -> glibc switch is very much unwanted if we want static builds—and we do) so I'm closing this
