### ISSUE TITLE
Help finding key names for special features on Apple function keys

### ISSUE THREAD

**Issue by all9n** [kmonad/kmonad#480]
Newer versions of MacBook changes some special features on the function keys. On my keyboard, F4 opens spotlight, F5 is dictation when tapped and Siri when held, F6 toggles Do Not Disturb. It seems there is no key code for these 3 yet(?). If that's the case, will these be added to KMonad in the future? Or maybe is there a way to work around this? Many thanks!

**Comment by MuhammedZakir** [comment]
`spotlight` and many other keys were added in `keycode-refactor` branch [1]. But Dictation, Siri and Do not Disturb are not available as Apple doesn't expose them to driver extensions (dext). There is nothing we can't do about those.

However, try building from `keycode-refactor` branch. You will have to comment out or remove three aliases to successfully build it [2]. Also, re-read the installation doc. Once you are done, try running KMonad in debug mode with `fallthrough` enabled, and see if the KMonad is able to detect keypresses of those other keys. If yes, you can use whatever name KMonad prints for those corresponding keys.

[1] https://github.com/kmonad/kmonad/blob/1d2276069fd781c4518082f1b36f3b2880667e79/src/KMonad/Util/Keyboard/Mac.hs#L173
[2] https://github.com/kmonad/kmonad/blob/1d2276069fd781c4518082f1b36f3b2880667e79/src/KMonad/App/Parser/Keycode.hs#L102-L104

**Comment by all9n** [comment]
Thanks for the quick response. I can confirm that `sptl` works as expected. Great!

However, I'm not sure I understand how to detect key presses as you described. I ran KMonad with `-ldebug --fallthrough` flags. WIthout knowing what to put in the `deflayer` block, I just get "Press f4", "Release f4" and so on. Is there anything I should change in my config before testing?

Also, after a quick look at the 2 links in Mac.hs, I think I need a lot more Googling for those to be helpful. Thanks for mentioning those anyways. I did find out that Karabiner-Elements seems to have at least the dictation/Siri button, according to [this comment](https://github.com/pqrs-org/Karabiner-Elements/issues/2516#issuecomment-750303670).

**Comment by MuhammedZakir** [comment]
> Thanks for the quick response. I can confirm that `sptl` works as expected. Great!

:+1:

> However, I'm not sure I understand how to detect key presses as you described. I ran KMonad with `-ldebug --fallthrough` flags. WIthout knowing what to put in the `deflayer` block, I just get "Press f4", "Release f4" and so on. Is there anything I should change in my config before testing?

Whatever is after `Press` is the name of the key you pressed; in your example, `f4`.

It looks like you're using KMonad from `master` branch. This will crash if it gets unknown keycodes. You should use `keycode-refactor` branch, at the very least, in Mac. When using `keycode-refactor` branch's KMonad, when debugging, it will print the keycode of unknown keys. You can add those keycodes in the code like I did below to use it and when you do, please open an issue or PR, so that others can also use it. :-) Don't remember to re-build and re-install if you add/change anything. I know this is a bit cumbersome, but hopefully, this will be solved when the option to directly use keycodes or create new keynames using keycodes in the config is added.

> Also, after a quick look at the 2 links in Mac.hs, I think I need a lot more Googling for those to be helpful. Thanks for mentioning those anyways. I did find out that Karabiner-Elements seems to have at least the dictation/Siri button, according to [this comment](https://github.com/pqrs-org/Karabiner-Elements/issues/2516#issuecomment-750303670).

Thanks! The 2 links we used are outdated. Dictation wasn't available in that doc (although, even if it was there, we wouldn't find out just by reading as the name used is `VoiceCommand` [1][2]). To use it, in `keycode-refactor` branch, in `src/KMonad/Util/Keyboard/Mac.hs`, add this line above line 167 [3]:
```
  , z 0xC [0xCF]       [ "siri" ]  -- or `dict`. real name: `VoiceCommand`
```

After that, build & install it and then, you can use `siri` or `dict` (whichever one you used -- inside brackets) for dictation/siri.

[1] https://github.com/pqrs-org/Karabiner-Elements/blob/81303e23d746e821e422d5a5abdc082d080882bc/src/share/types/momentary_switch_event_details/consumer_key_code.hpp#L11
[2] https://developer.apple.com/documentation/hiddriverkit/3201483-consumer/khidusage_csmr_voicecommand
[3] https://github.com/kmonad/kmonad/blob/1d2276069fd781c4518082f1b36f3b2880667e79/src/KMonad/Util/Keyboard/Mac.hs#L167

**Comment by all9n** [comment]
Hmmm I think _am_ using the `keycode-refactor` branch. My confusion mostly comes from [this section in our FAQ](https://github.com/kmonad/kmonad/blob/master/doc/faq.md#mac). I'm under the impression that we can't get special keycodes this way, unless things have changed in this branch(?).

Just to be clear, this is my config:

```clojure
(defcfg
  input (iokit-name "Apple Internal Keyboard / Trackpad")
  output (kext)
  fallthrough true
  allow-cmd false
  )
(defsrc f4 f5 f6)
(deflayer default sptl siri _)
```

Pressing the F4 key launches spotlight but KMonad still says `Got: Press f4` and `Got: Release f4`. Same story for the voice command button. (Yay it works. Thanks! Also I have no idea how you're supposed to look at that name and think, "Ok this is the key I need".)

**Comment by MuhammedZakir** [comment]
> Hmmm I think _am_ using the `keycode-refactor` branch.

My mistake.

> My confusion mostly comes from [this section in our FAQ](https://github.com/kmonad/kmonad/blob/master/doc/faq.md#mac). I'm under the impression that we can't get special keycodes this way, unless things have changed in this branch(?).
> 
> Just to be clear, this is my config:
> 
> ```clojure
>  ;; --snip defcfg--
> (defsrc f4 f5 f6)
> (deflayer default sptl siri _)
> ```

KMonad only handles/catches keys mentioned in `defsrc`. All other keys' presses are _ignored_ if `falthrough` is `true`, or _blocked` if `fallthrough` is `false`. Your config is not wrong if you only want to emulate what Apple does (see the example config linked in the FAQ you mentioned), but you won't be able to remap special keys like `sptl`, volume/brightness keys, etc, or any other keys, because they are not in `defsrc`. This is only a problem if you want to change position of those keys - for example, if you use more than one laptop and want same config in all of them.

> Pressing the F4 key launches spotlight but KMonad still says `Got: Press f4` and `Got: Release f4`. Same story for the voice command button.

`Got` shows what "input" event it "got"/"received". Here, 2 events, a press and a release of `f4`. That's what you did. If you look at the debug output, you will see `Put: Press sptl` and `Put: Release sptl` somewhere after those `Got`s - this shows what events it "output"/"put"/"emit" -- this is where you see what your config did when you pressed a key because names shown in `Put` will change depending on your layer and buttons.

> (Yay it works. Thanks! _[...]_

You're welcome! :-)

> _[...]_  Also I have no idea how you're supposed to look at that name and think, "Ok this is the key I need".)

Simply put, that only works for simple keys (what you see in a "basic" keyboard). For other keys, especially multimedia and special keys, we will have to test it to see what `keycode`s we get when we press them (see below for more details).

> Update: This looks like the keycode for Do Not Disturb, https://developer.apple.com/documentation/kernel/1641458-anonymous/khidusage_gd_donotdisturb.

It seems true, but unfortunately, names can be deceiving. We will have to test it.

> I have yet to figure out how to add it to `src/KMonad/Util/Keyboard/Mac.hs` properly. (Is that even the right place?) At the moment the new button does nothing.

Apple keycode has 2 parts - usage page and usage. For example, in `z 0xC [0xCF] [ "siri" ], `0xC` is usage page and `0xCF` is usage. This is what matters for KMonad, we only need these. What names Apple uses for these don't matter. We only follow them for consistency.

In debug output, if KMonad knows the key you pressed, it will show its name in `Got: Press <name>` and you can use that name. If it doesn't know, then it will show keycode in the format `(usage_page, usage)`. To use it, you will have to create a new keyname in the code with that keycode.

For example, if you want to add a new key, say `kHIDUsage_GD_DoNotDisturb`, then you first have to know the usage page of that key. Generally, you can infer usage page from the name itself; here "GD" means "GenericDesktop". You can find a list of  usage pages and its constants here [1] and constants for `usage`s from correspondig usage page here [2]. To sum it up, we need to add this in `keycodeNames` in `src/KMonad/Util/Keyboard/Mac.hs`.
```
, z 0x01 [0x9B] ["dnd"]
```
The exact location doesn't matter as long as it is inside the opening and closing square brackets. But we do group usages of same usage pages to make it easier to understand/edit code.

[1] https://developer.apple.com/documentation/hiddriverkit/3201477-usage_pages
[2] https://developer.apple.com/documentation/hiddriverkit/hid_usage_tables

---

P.S. You may also use Karabiner-EventViewer to get the keycode. IIRC, latest versions shows them.

**Comment by MuhammedZakir** [comment]
@_tekezo_ already tested `kHIDUsage_GD_DoNotDisturb` and it didn't work [1]. Also, we can only support usage pages that Karabiner-dext supports, and when I looked the code, it doesn't support `GenericDesktop` usage page [2]. Previously, I thought it supports all usage pages, at least the ones related to keyboard and mouse, but it only supports
1. kHIDPage_KeyboardOrKeypad (0x07)
2. kHIDPage_Consumer (0x0C)
3. kHIDPage_AppleVendorKeyboard (0xff01)
4. kHIDPage_AppleVendorTopCase (0x00ff)

It also supports mouse and thus, may support other usage pages, but I don't know anything about that.

[1] https://github.com/pqrs-org/Karabiner-Elements/issues/2516#issuecomment-965835171
[2] https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice/tree/main/include/pqrs/karabiner/driverkit/virtual_hid_device_driver/hid_report

**Comment by all9n** [comment]
> Also, we can only support usage pages that Karabiner-dext supports ...

That makes a lot of sense. I should have realized this when I found out those keycode doesn't really match Apple's website. It says it uses HID Usage Tables Version 1.12, which seems pretty dated[1]. I guess for the time being I'll just work around this with F19. 

Also, thanks a lot for the _extremely_ detailed explanation. Really appreciate it! : )

[1] https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice/blob/ee00f86a52bdcb0d808abc018dda141bebcd7308/src/Client/vendor/cget/pkg/pqrs-org__cpp-hid/install/include/pqrs/hid/usage_page.hpp#L29-L32
