### ISSUE TITLE
[Windows] Printscreen doesn't work when kmonad is running

### ISSUE THREAD

**Issue by 6gk** [kmonad/kmonad#489]
Quick example config:

```
(defcfg
	input  (low-level-hook)
	output (send-event-sink)

	fallthrough   true
	allow-cmd     true
)

(defsrc         esc grv)
(deflayer base  grv esc)
```

Running kmonad via a shortcut with the Target of `C:\Programs\kmonad.exe C:\Programs\kmonad.kbd` and the start directory being `C:\Programs`

Version: `v0.4.1` (latest release, i don't want to compile on windows)

When using [autohotkey as a subpar alternative to xev](https://superuser.com/questions/348070/equivalent-for-xev-on-windows), it shows `2A  000	a	d	1.91	not found` when pressing the key, as opposed to `2C  137	 	d	1.00	PrintScreen` (`VK  SC  Type  Up/Dn  Elapsed  Key`).

**Comment by MuhammedZakir** [comment]
Pass `--log debug` cli option to `kmonad.exe` and post the output you get when you press `PrintScreen` here.

**Comment by 6gk** [comment]
![image](https://user-images.githubusercontent.com/40295114/155208518-a57d2b6d-815c-4016-8c1e-b53fc3953b6e.png)

**Comment by MuhammedZakir** [comment]
Apparently, there are two "print" keys and unfortunately, both of them were given the same name in KMonad. We will have to update the code to fix this.

https://github.com/kmonad/kmonad/blob/2cc865bcfc255e16225f1980d214188a99205297/src/KMonad/Keyboard/IO/Windows/Types.hs#L165-L167

https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes:
```
VK_PRINT	0x2A	PRINT key
VK_EXECUTE	0x2B	EXECUTE key
VK_SNAPSHOT	0x2C	PRINT SCREEN key
```

**Comment by 6gk** [comment]
Whoops, sorry, didn't see that email!

> Edit: What are the values in second column?

I should probably have formatted it differently, I'm pretty sure it was:
```
VK SC  Type Up/Dn Elapsed Key
2A 000 a    d     1.91    not found  # pressing when kmonad is running
2C 137      d     1.00    PrintScreen  # pressing when kmonad isn't running
```

> And also why does it show "not found" for 0x2A? (note: I haven't used AHK.)

I'm not certain, but I would assume it's because kmonad is absorbing keypresses (even those not in the config) & repeating them -- it absorbs the print keypress, but repeats an invalid key, leading to software not being able to recognize it (including the super+print built-in bind which is how I noticed)

**Comment by MuhammedZakir** [comment]
>> And also why does it show "not found" for 0x2A? (note: I haven't used AHK.)
> I'm not certain, but I would assume it's because kmonad is absorbing keypresses & repeating them (either the new key if it's been redefined, or the same one if it's not) -- it absorbs the print keypress, but repeats an invalid key, leading to software not being able to recognize it (including the super+print built-in bind which is how I noticed)

KMonad only bothers about sending "keycodes" (or executing shell cmds) and here, AHK correctly prints `0x2A`. What I'm confused is why it is showing "not found" instead of "Print" or something. (not addressing you... just saying.)

> Thanks for the help & the snippet, I guess that means the plain print key is only there for legacy things? ​ Strange.

if you're fine with compiling, then please try this branch -- https://github.com/MuhammedZakir/kmonad/tree/windows-printscreen-fix. This will hopefully fix this issue.

To test this, use `pscrn`[1]. Personally, I would like to use `PrintScreen` as `prnt` and rename current Windows' print key to a different name to get a consistent name across OSes. But I didn't do that because it may break somebody's workflow and I am not sure what that print key does. Need input from other KMonad Windows users on that key and whether you are okay with changing the name.

[1] https://github.com/MuhammedZakir/kmonad/commit/35dbd7bd7eca9e218ffbaaee71d5293bcb3374fe#diff-f9285f2e5bcb4dde1c80a095a845d0ceab27f847339646678ecba056387731beR415

**Comment by 6gk** [comment]
Cheers! ​ I'll see if I can try it out within the next few days!

**Comment by 6gk** [comment]
@MuhammedZakir Thank you so much!

This fixes the issue both when pscrn isn't in the config, and when not in the config.

I can screenshot to disk again 🎉

**Comment by MuhammedZakir** [comment]
> @MuhammedZakir Thank you so much!

You're welcome! :-)

> This fixes the issue both when pscrn isn't in the config, and when not in the config.
> 
> I can screenshot to disk again tada

When does "fix issue when `pscrn` is not in the config" mean? Are you able to take screenshot with `prnt`? If yes, then what does `pscrn` do?

**Comment by 6gk** [comment]
> When does "fix issue when pscrn is not in the config" mean? 

Previously, the physical print screen button did nothing when kmonad was open, regardless of if the key was specified in the kmonad config or not.

Now, I am able to both use the button when it's not specified in the config, and I am able to remap it in the config -- so it's working as it should thanks to your fix.

> Are you able to take screenshot with prnt? 

Sorry for the unclarity -- No: `prnt` is just ignored (as in, changes nothing & print button works fine) if it's specified in the config, but `pscrn` is able to remap it perfectly.

**Comment by MuhammedZakir** [comment]
Understood. :-)

Should I make a PR with this change? Or should I do it after changin `pscrn` to `prnt` and `print` to `prnt2` or something? That's what users would expect, but wondering if that would break existing users' workflow.

pinging known Windows users: @whitbur @Veanvi @jayrajput

**Comment by whitbur** [comment]
Oh huh, I guess I didn't notice this because I use super+shift+S to take screenshots.

If hitting the PrintScreen button on other OSes sends `prnt` in kmonad, personally I'd try to maintain that behavior over supporting whatever VK_PRINT is supposed to do (maybe like what Ctrl+P does in most contexts?). I use kmonad regularly on both Mac and Windows, so the less I have to change between the two config files, the better.

**Comment by 6gk** [comment]
> Oh huh, I guess I didn't notice this because I use super+shift+S to take screenshots.

I use both, but I tend to like using screenshots for archiving as well - and super+print is just the easiest way to do that.

> If hitting the PrintScreen button on other OSes sends prnt in kmonad, personally I'd try to maintain that behavior over supporting whatever `VK_PRINT` is supposed to do

I'm not sure I understand -- `VK_PRINT` / `0x2A` is `prnt`, the current one -- And on windows, [that key appears to be a legacy thing](https://stackoverflow.com/questions/5815471/whats-the-purpose-of-vk-print)

`VK_PRINT_SCREEN` / `VK_SNAPSHOT` / `0x2C` is `pscrn`, the one Muhammed added in their fork to fix windows.

---

I agree that I'd prefer changing the config as little as possible when using on another OS, so I think the best solution might be making `prnt` stay as it is on linux/mac (`0x2A`), but make it `0x2C` on Windows -- I'm not quite sure on how different `0x2A`/`0x2C` are on Linux & Mac (and I'd prefer not unnecessarily breaking some niche workflows if they're not treated identically), but I know that `0x2A` is useless on windows.

**Comment by whitbur** [comment]
Yep, I think we're in agreement.

I don't think we should change the existing behavior on other OSes, and I don't think it's worth maintaining the existing `VK_PRINT` binding on Windows. I'd be happy to just drop it, since as you say it's a legacy thing. That would make this a one-line change, [setting line 537 here to 0x2C](https://github.com/kmonad/kmonad/blob/master/src/KMonad/Keyboard/IO/Windows/Types.hs#L537). No need to change `src/KMonad/Keyboard/Keycode.hs` at all.

If we are going to add another keycode to differentiate the two on Windows, then I'd prefer that the new Windows-specific keycode refers to `VK_PRINT` instead of `VK_PRINT_SCREEN`/`VK_SNAPSHOT`, since this would keep configuration consistent across OSes. This is different from what Muhammed's change shows, which would now require configuration on Windows to show `pscrn` where other OSes still need to show `prnt`.

**Comment by MuhammedZakir** [comment]
Created a PR that does -- change `prnt` to refer to `PrintScreen`(`0x2C`) on Windows and `prntl` to legacy print (`0x2A`). This will give consistent result across OSes. Can you guys please review it?
