### ISSUE TITLE
Type dynamic phrase

### ISSUE THREAD

**Issue by jsilve24** [kmonad/kmonad#529]
I would like to have an tap-macro where the macro changes depending on the results of a script. That is, I have some script "foo.sh" that when run outputs a string. I would like to be able to exectue that string as a tap-macro in kmonad. Is this possible? 

**What I have tried so far:**
At the moment I have a script that computes the string and then calls xdotool to simulate the key presses which works perfectly just not when I try to bind it with cmd-button. That is, xdotool and kmonad don't seem to play nice together. Here is an example

bind `(cmd-button "xdotool type 'asdf'")` to some key in kmonad. Try to exectue, it does nothing. But typing `xdotool type 'asdf'` on the command line works fine.

**Comment by MuhammedZakir** [comment]
Not possible atm.

About `xdotool`: It's probably because when you run KMonad it doesn't inherit `DISPLAY` env var. Try running `kmonad` with logging set to debug (see `kmonad h`). It will show something when you execute that button.

**Comment by Cobertos** [comment]
I was able to get this to work without needing to do anything with `$DISPLAY`. I just had to make sure to `allow-cmd true` in my config and when doing `kmonad ~/.config/kmonad.kbd -l debug` it shows it executing the command and it properly types out `'asdf'`

Still, it would be nice to be able to use type-macro instead of having to rely on xdotool.

**Comment by slotThe** [comment]
When you run `kmonad`, it inherits your current environment. This is a problem if, for example, you start KMonad as a systemd service or similar
