### ISSUE TITLE
Is possible to run kmonad withouth root?

### ISSUE THREAD

**Issue by M3cubo** [kmonad/kmonad#617]
If I run something like this, kmonad is running fine:
 
`sudo /home/user/apps/kmonad "/home/user/.config/kmonad/config.kbd"`

But if I run the command withouth the sudo, it gives me this error:

**kmonad: /dev/uinput: openFd: permission denied (Permission denied)**

In case any of these have relation with the issue, the executable show these permissions when I run `ls -l`:

**-rwxrwxr-x 1 user user 3570344 sep  8 17:00 kmonad**

And the uinput.rules files show these:

**-rwxr-xr-x 1 root root  78 sep  8 17:53 90-uinput.rules**

I also followed the uinput group changes that the guide says.

**Comment by rrveex** [comment]
Doesn't matter who owns `kmonad` or `90-input.rules`.
/dev/uinput: openFd: permission denied
This means your `user` doesn't have rights for `/dev/uinput`
Check with `ls -l /dev/uinput` whether the udev rule worked (group should be `kmonad`) and with `groups` whether your user belongs to that group.

**Comment by rrveex** [comment]
The command `groups` tells you which groups you belong to, not which groups exist on the system (`cat /etc/group` for that).

> `crw-rw---- 1 root uinput 10, 223 sep 10 19:40 /dev/uinput`

This says something like: "the file /dev/uinput can be read and modified by the user `root` and any member of the group `uinput`; everyone else has no rights at all on that file".

In your case, the easiest way to gain access is to add yourself to the group `uinput`. Assuming your user name is `user`, type as root (or with `sudo`) something like: `usermod -G uinput -a user`. Log-out and -in again (or restart) for that to take effect, then check with `groups` (`uinput` should be in the list of groups you belong to).

Please note this doesn't have anything to do with kmonad, it's basic linux file permissions - if you (your user) wants access (via a program you execute) to some resource (via the file `/dev/uinput` for instance), the system has to be setup to allow that.

> Can that change of group permissions give errors...

If you add your user to the `uinput` group you're just giving youreself (your user) more power than your distro creators thought necessary. This is possibly a security risk. I don't think there's any problem here, but you shouldn't get security advice from some random person on github :)

If you change the group on `/dev/uinput` (like from current/default `uinput`-group to a new `kmonad`-group) you might break some functionality (e.g. another program) relying on the default (I don't think you'll get any problems because of this either).

**Comment by M3cubo** [comment]
Many tanks @rrveex, I am still learning about Linux permissions, but you have brought a clear logic about this topic. Finally I used the:

`usermod -G uinput -a user`

to put my user in the uinput group, so everything works as I wanted. I will remember these commands. 

I close this issue as it is now solved. Again, many thanks and have a good day!

**Comment by lowy** [comment]
But no uinput group in the linuxmint, how do it ?
ls -l /dev/uinput         
crw-rw---- 1 root root 10, 223  2月 15 13:09 /dev/uinput

**Comment by KaitlynEthylia** [comment]
@lowy 

I suggest you read [The FAQ](https://github.com/kmonad/kmonad/blob/master/doc/faq.md#q-how-do-i-get-uinput-permissions)

> If the `uinput` group does not exist, create a new group with: `sudo groupadd uinput`

**Comment by lowy** [comment]
> @lowy
> 
> I suggest you read [The FAQ](https://github.com/kmonad/kmonad/blob/master/doc/faq.md#q-how-do-i-get-uinput-permissions)
> 
> > If the `uinput` group does not exist, create a new group with: `sudo groupadd uinput`

thank tell me , it's fine.
