### ISSUE TITLE
Syntax highlighters for Emacs/Vim

### ISSUE THREAD

**Issue by david-janssen** [kmonad/kmonad#69]
If anyone is up to writing a syntax highlighter for `kbd` configuration files, that would be amazing :-)

**Comment by WisdomWolf** [comment]
VSCode as well!

**Comment by MaxGyver83** [comment]
I do `:set filetype=lisp` in vim. That's not perfect but still much better than the default highlighting.

**Comment by precondition** [comment]
> I do `:set filetype=lisp` in vim. That's not perfect but still much better than the default highlighting.

The clojure syntax highlighter is a little nicer for kbd files, especially in regards to `t` in the keymap and button-macros

**Comment by MaxGyver83** [comment]
> The clojure syntax highlighter is a little nicer for kbd files, especially in regards to `t` in the keymap and button-macros

You are right. It looks better with `:set filetype=clojure`. The biggest remaining issue is that the `"` character within `deflayer` blocks destroys the syntax highlighting from there until the end of the file. Escaping it fixes the syntax highlighting but KMonad doesn't accept `\"`. So I just replaced all occurrences of `"` with `S-'`. Now it looks good enough for me.

**Comment by david-janssen** [comment]
Yeah, having issues here and there with those characters as well, maybe an alias like `quot` would be a good idea as well.

**Comment by MaxGyver83** [comment]
Yes, I also searched for an alias. That would be less ambiguous than `S-'`.

**Comment by Hugo-Heagren** [comment]
I've written a [vim syntax file](https://git.hugoheagren.com/Hugo-Heagren/KMonad.vim). I'm pretty sure it covers everything. This is my first time writing a syntax file though, so I'm not sure if I've got all the colour groups quite right. Let me know if there's anything I should change/add. It also includes syntax folding and matchit-jumping (<kbd>%</kbd> in vim) between multiline comment start/end markers.

I'm not sure how best it should be integrated into the kmonad world over all. I'm trying to move away from github to my own gitea instance, but that might not be great for something public which should be stable and accessible all the time. Maybe this is a good use for the kmonad organisation? I'd be happy to transfer ownership somehow to them, or have it in a repo owned by David or something. Whatever works...

**Comment by habibalamin** [comment]
There's also [mwgkgk/kmonad-vim](https://github.com/mwgkgk/kmonad-vim).

**Comment by slotThe** [comment]
@Hugo-Heagren

> I'm not sure how best it should be integrated into the kmonad world over all. I'm trying to move away from github to my own gitea instance, but that might not be great for something public which should be stable and accessible all the time. 

I had similar concerns with the Emacs mode, but ultimately decided that if the project wants to be on GitHub then it's perhaps best if all parts were.  

> Maybe this is a good use for the kmonad organisation? I'd be happy to transfer ownership somehow to them, or have it in a repo owned by David or something. Whatever works...

Yeah this is what I currently think would be the best approach.  That approach was discussed a bit in #142 but I think we still aren't sure if transferring ownership on here would leave the issue tracker and open pr's alone.

**Comment by MaxGyver83** [comment]
@Hugo-Heagren : Your link is dead. It gives me: **502 Bad Gateway**
@habibalamin : I have tried your `kmonad-vim` but I don't get any syntax highlighting at all. But it sets the filetype to `kmonad`.

**Comment by Hugo-Heagren** [comment]
@MaxGyver83 link should be back up now. You checked at a bad time -- it was down for a different project I'm working on, which is a good example of why I want it kept somewhere less volatile!

It should be up for the next few days at least, so have a look. The repo isn't huge either, so you could clone it locally if you want to play around with it or whatever.

**Comment by habibalamin** [comment]
@MaxGyver83 ah, my apologies, I didn't actually test out that Vim plugin yet, I was just putting it out there as an option, since that's what the issue was about, and I thought it would be nice to collate all the options.

I'm not the author of that plugin, by the way, I was just putting it into the ring as an option. Honestly, I should have tried it beforehand, but I haven't even gotten around to installing KMonad itself yet; I'm still just reading the docs.

**Comment by MaxGyver83** [comment]
@habibalamin : No problem.

@Hugo-Heagren : I have cloned it and it looks great. Thanks for sharing!

**Comment by MaxGyver83** [comment]
@Hugo-Heagren : How can I create issues? I couldn't find where to register in your Gitea.

**Comment by slotThe** [comment]
On Thu, Apr 08 2021 13:45, Max Schillinger wrote:
> @Hugo-Heagren : How can I create issues? I couldn't find where to
> register in your Gitea.

It's self-hosted, so I would expect the answer to be "email me" :)

**Comment by Hugo-Heagren** [comment]
@MaxGyver83 short answer: don't, wait until it's no longer just self-hosted.

Longer, real answer: registration is disabled at the moment. This is for two
reasons:
- I have a couple of ~~friends~~ acquaintances who would think it hilarious fun to make lots of accounts and file hundreds of issues on my site, which I'm not wild about.
- It's meant for personal projects, for me to host my stuff. This is partly because anything worth keeping that I build should be kept somewhere *else* (as the history of this thread shows, because my gitea is sometimes down). Keeping registration off and making it impossible for people to file issues (hopefully) forces people to fork/take ownership of anything they need, away from my volatile gitea instance. Basically if I don't let you use it as a dev platform, I force you to use a better platform (in terms of public accessibility and future proofing).

*Sooo* ideally, hold off until the repo has be transferred to the @kmonad
organistion (everyone seems to agree that this would be a good course of action right?). This shouldn't be too difficult because there currently aren't any open issues or pull requests to worry about.

All that said, if you have a pressing issue, then you can [email me](mailto:hbh1g18@soton.ac.uk). If there's a good reason then I'm happy to re-enable registration and you can post proper issues, but I'd rather not.

**Comment by MaxGyver83** [comment]
No problem, I can wait.

**Comment by david-janssen** [comment]
Popping in as the person who has the power to fix things: how exactly would we like to resolve this?

I am happy moving kmonad to the kmonad organisation, but I'm under the impression we'd loose all of our issues and pull-requests and history, which is the only reason I've kept hosting it on my account.

In regards to hosting syntax-highlighters, if you think you could get around your acquaintances by hosting it here, I'd be happy to just open a repo on my account and make you a fully empowered collaborator. I have no interest in doing anything emacs/vim related at the moment, so it would be 100% your responsibility, but I'm fine hosting it here.

Happy to hear other solutions as well

**Comment by thoelze1** [comment]
@david-janssen Apparently issues, PRs, etc are transferred when a repository is transferred to another account:

https://docs.github.com/en/github/administering-a-repository/transferring-a-repository

Maybe it would be a good idea so that you could maintain your own fork and so that the kmonad organization could host both kmonad and related highlighters

**Comment by david-janssen** [comment]
And it's done! We have a kmonad organization with a kmonad repo. And you were right, all the issues and such just transferred over. I must have misread when I was looking into this a few months ago.

So, @Hugo-Heagren, would you like me to create a repo in the kmonad project for emacs/vim code and assign you to it? Let me know exactly what/how you want to do, and I'll see how I can help.

**Comment by slotThe** [comment]
On Thu, May 13 2021 08:23, David Janssen wrote:
> And it's done! We have a kmonad organization with a kmonad repo. And
> you were right, all the issues and such just transferred over. I must
> have misread when I was looking into this a few months ago.

That's good news!  I added the repo for the Emacs mode to it.

**Comment by Hugo-Heagren** [comment]
> would you like me to create a repo in the kmonad project for emacs/vim code and assign you to it?

@david-janssen, that works for me. Create the repo and I'll just push in everything I have already. Then @slotThe can raise their issue there.

**Comment by david-janssen** [comment]
created https://github.com/kmonad/kmonad-vim, invited @Hugo-Heagren for write-access, so you should be able to manage issues and pull requests yourself. Closing this now, since we have both a repo for emacs and one for vim.

**Comment by molleweide** [comment]
Can everybody access all the old issues? I get 404 when I try to find some of the issues I had planned to read. (in my specific case #67 )

**Comment by Hugo-Heagren** [comment]
All sorted, it's up on github now.
