### ISSUE TITLE
Numerous Build warnings

### ISSUE THREAD

**Issue by hirak99** [kmonad/kmonad#881]
When the package is built on Arch, it emits a lot of warnings.

Log: https://builds.garudalinux.org/repos/chaotic-aur/logs/kmonad-git.log

This was flagged while building for Chaotic AUR, a repository system for Arch packages, where I requested to add kmonad-git (i.e. kmonad from git HEAD): https://github.com/chaotic-aur/packages/issues/3293#issuecomment-2325116621

The binary as far as I can tell is working correctly.

Flagging to check if the warnings are expected.

**Comment by jokesper** [comment]
Some are due to Arch installing specific library versions. Most are in dependencies used by KMonad. That being said I don't know if it's like this due to old package versions being used (maybe due to the specific versions available on Arch which forces older versions of other packages). I will investigate this further later.
