### ISSUE TITLE
KMonad Binary not found when running with sudo on Mac

### ISSUE THREAD

**Issue by CampAsAChamp** [kmonad/kmonad#911]
Hi all, not sure if this is the right place to report this, but never seen something like this before. Posting my terminal output. 

I have installed installed kmonad successfully (I think?) and running it without sudo seems fine(?).  But when I try and run it with `sudo` I'm getting a command not found error.

Any ideas or pointers?

<img width="808" alt="image" src="https://github.com/user-attachments/assets/f1bded6f-c16a-4ef6-8a00-73b8eb6160cd">

**Comment by jokesper** [comment]
I see you already closed this, so you probably found the issue.
But to be sure:
The problem is that sudo doesn't inherit the path, you should probably move kmonad to a location not writable by your user and include it in a path globally. I.e. move kmonad to `/bin` / `/usr/bin` or whatever mac is using.
You could also use `sudo $(which kmonad)` to run it with an absolute path

**Comment by CampAsAChamp** [comment]
Yup, didn't realize sudo doesn't inherit the path. I moved the executable like you said and was good after that!

This is not a KMonad issue but this was the first time I've seen this issue so I didn't know where else to go. Thanks for responding anyways!
